---
title: "Brazilian airline market data cleaning"
author: "João Ricardo Tonin"
date: "31/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      comment = NA,
                      warning = FALSE,
                      error = FALSE, 
                      message = FALSE,
                      tidy = TRUE)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
print(getwd())
dwdir = print(getwd())

{ 
  # Check if the packages that we need are installed
  want = c("tidyverse", "plm", "texreg", "lmtest", "knitr", "data.table")
  have = want %in% rownames(installed.packages())
  # Install the packages that we miss
  if ( any(!have) ) { install.packages( want[!have] ) }
  # Load the packages
  junk <- lapply(want, library, character.only = T)
  # Remove the objects we created
  rm(have, want, junk)
} # Import packages

```

```{r cleanning, include = FALSE}

# setting directories
dwcomraw = paste0(dwdir, "/data/combined/raw")
dwcomrds = paste0(dwdir, "/data/combined/rds")
dwfinrds = paste0(dwdir, "/data/final")
dwbasraw = paste0(dwdir, "/data/basic/raw")
dwbasrds = paste0(dwdir, "/data/basic/rds")
dwpriraw = paste0(dwdir, "/data/prices/raw")
dwprirds = paste0(dwdir, "/data/prices/rds")

{
  # setting the directory  
  setwd(dwcomraw) 
  
  # creating a list of .CSV databases
  temp = list.files(pattern = "*.txt") 
  
  for (file in 1:36){ 

    # setting the directory    
    setwd(dwcomraw) 
    
    # get the read_delim function working
    vfiles = read_delim(temp[file], ";", 
                        escape_double = FALSE, 
                        locale = locale(decimal_mark = ",", 
                                        grouping_mark = ".", 
                                        encoding = "ISO-8859-1"), 
                        trim_ws = TRUE)
    
    # organizing database
    COMBINADA = vfiles %>% 
      mutate(seat_com = nr_passag_pagos) %>% ungroup() %>%
      select("id_empresa", "nr_voo", "hr_partida_real", "dt_partida_real", 
             "sg_icao_origem", "sg_icao_destino", "hr_chegada_real", "dt_chegada_real",
             "seat_com")
      
    # setting the directory      
    setwd(dwcomrds) 
    
    # Saving a single object to a file
    saveRDS(COMBINADA, paste(file, ".rds"))
 
  } # Creating looping for .txt files
  
  {
    # Step 1: set the working directory (where files are saved)
    setwd(dwcomrds) 
    
    # Step 2: get all the right file names
    file_names = list.files(getwd())
    file_names = file_names[grepl(".rds",file_names)]
    
    # Step 3: get the read.csv function working
    files = readRDS("1 .rds")
    
    # Step 4: use lapply to apply the read.csv function to all values of file_names
    files = lapply(file_names, readRDS)
    list = files
    files = rbindlist(files, fill = TRUE)
    
    # check structure of new data set
    str(files)
    
    # rename
    COMBINADA = files
    
    
  } # Join databases
  
  # Dropping unnecessary databases
  remove(list = c("files", "file_names"))
  
  # transform NA to 0
  COMBINADA$seat_com[is.na(COMBINADA$seat_com)] = 0
  
  COMBINADA = COMBINADA %>% group_by(id_empresa, nr_voo, hr_partida_real, dt_partida_real,
                                 sg_icao_origem, sg_icao_destino, hr_chegada_real, 
                                 dt_chegada_real) %>%
    dplyr::summarise(seat_com = sum(seat_com))
  
  # renaming database
  COMBINADA_Essay_II = COMBINADA
  
  # setting the directory      
  setwd(dwfinrds) 
  
  # Saving a single object to a file
  saveRDS(COMBINADA_Essay_II, "COMBINADA_Essay_II.rds")

} # Transforming Combinated database

{
  # setting the directory  
  setwd(dwbasraw) 
  
  # creating a list of .CSV databases
  temp = list.files(pattern = "*.txt") 
  
  for (file in 1:36){ 
    
    # setting the directory    
    setwd(dwbasraw) 
    
    # get the read_delim function working
      vfiles = read_delim(temp[file], ";", 
                          escape_double = FALSE, 
                          locale = locale(decimal_mark = ",", 
                                          grouping_mark = ".", 
                                          encoding = "ISO-8859-1"), 
                          trim_ws = TRUE)
    
    # organizing database
    BASICA = vfiles %>% 
      mutate(seat_bas = nr_passag_pagos) %>% ungroup() %>%
      select("id_empresa", "nr_voo", "hr_partida_real", "dt_partida_real", 
             "sg_icao_origem", "sg_icao_destino", "hr_chegada_real", "dt_chegada_real", 
             "sg_empresa_icao", "id_di", "ds_di", 
             "ds_grupo_di", "nr_ano_referencia", "nr_ano_mes_referencia", 
             "ds_tipo_linha", "ds_natureza_etapa", "lt_combustivel", "nr_assentos_ofertados",
             "kg_payload", "km_distancia", "seat_bas", "nr_passag_gratis", 
             "kg_bagagem_livre", "kg_bagagem_excesso","kg_carga_paga", "kg_carga_gratis",
             "kg_correio", "nr_decolagem", "nr_horas_voadas", "kg_peso", 
             "nr_ask", "nr_rpk", "nr_atk", "nr_rtk")

    
    # setting the directory      
    setwd(dwbasrds) 
    
    # Saving a single object to a file
    saveRDS(BASICA, paste(file, ".rds"))
    
  } # Creating looping for .txt files
  
  {
    
    # Step 1: set the working directory (where files are saved)
    setwd(dwbasrds) 
    
    # Step 2: get all the right file names
    file_names = list.files(getwd())
    file_names = file_names[grepl(".rds",file_names)]
    
    # Step 3: get the read.csv function working
    files = readRDS("1 .rds")
    
    # Step 4: use lapply to apply the read.csv function to all values of file_names
    files = lapply(file_names, readRDS)
    files = rbindlist(files, fill = TRUE)
    
    # check structure of new data set
    str(files)
    
    # rename
    BASICA = files
    
    
  } # Join databases
  
  # Dropping unnecessary databases
  remove(list = c("files", "file_names"))

  BASICA = BASICA %>% mutate_at(c(17:34), ~replace(., is.na(.), 0)) %>% ungroup() %>%
    group_by(id_empresa, nr_voo, hr_partida_real, dt_partida_real, sg_icao_origem,
             sg_icao_destino, hr_chegada_real, dt_chegada_real, sg_empresa_icao,
             id_di, ds_di, ds_grupo_di, nr_ano_referencia, nr_ano_mes_referencia,
             ds_tipo_linha, ds_natureza_etapa) %>%
    dplyr::summarise(lt_combustivel = sum(lt_combustivel),
                     nr_assentos_ofertados = sum(nr_assentos_ofertados), 
                     kg_payload = sum(kg_payload), 
                     km_distancia = sum(km_distancia),
                     seat_bas = sum(seat_bas), 
                     nr_passag_gratis = sum(nr_passag_gratis), 
                     kg_bagagem_livre = sum(kg_bagagem_livre), 
                     kg_bagagem_excesso = sum(kg_bagagem_excesso),
                     kg_carga_paga = sum(kg_carga_paga), 
                     kg_carga_gratis = sum(kg_carga_gratis),
                     kg_correio = sum(kg_correio), 
                     nr_decolagem = sum(nr_decolagem),
                     nr_horas_voadas = sum(nr_horas_voadas), 
                     kg_peso = sum(kg_peso),
                     nr_ask = sum(nr_ask), 
                     nr_rpk = sum(nr_rpk),
                     nr_atk = sum(nr_atk), 
                     nr_rtk = sum(nr_rtk))
  
  # renaming database
  BASICA_Essay_II = BASICA 
  
  # setting the directory      
  setwd(dwfinrds) 
  
  # Saving a single object to a file
  saveRDS(BASICA_Essay_II, "BASICA_Essay_II.rds")
  
} # Transforming Basic database

{
  # setting the directory  
  setwd(dwpriraw) 
  
  # creating a list of .CSV databases
  temp = list.files(pattern = "*.CSV") 
  
  for (file in 1:35){ 
    
    # setting the directory    
    setwd(dwpriraw) 
    
    # get the read_delim function working
    vfiles = read_delim(temp[file], ";", 
                        escape_double = FALSE, 
                        locale = locale(decimal_mark = ",", grouping_mark = "."), 
                        trim_ws = TRUE)
    
    # organizing database
    PRECOS = vfiles %>% mutate(RECEITA = ASSENTOS*TARIFA) %>% 
      group_by(ANO, MES, EMPRESA, ORIGEM, DESTINO) %>%
      dplyr::summarise(ASSENTOS = sum(ASSENTOS),
                       RECEITA = sum(RECEITA))
    
    # Change the names of the columns
    names(PRECOS)[names(PRECOS) == "ASSENTOS"] = "seat"
    names(PRECOS)[names(PRECOS) == "RECEITA"] = "revenue"
    names(PRECOS)[names(PRECOS) == "EMPRESA"] = "airline"
    names(PRECOS)[names(PRECOS) == "ANO"] = "year"
    names(PRECOS)[names(PRECOS) == "MES"] = "month"
    names(PRECOS)[names(PRECOS) == "ORIGEM"] = "air_dep"
    names(PRECOS)[names(PRECOS) == "DESTINO"] = "air_arr"
    
    # setting the directory      
    setwd(dwprirds) 
    
    # Saving a single object to a file
    saveRDS(PRECOS, paste(file, ".rds"))
    
    
  } # Creating looping for .txt files
  
  {
    
    # Step 1: set the working directory (where files are saved)
    setwd(dwprirds) 
    
    # Step 2: get all the right file names
    file_names = list.files(getwd())
    file_names = file_names[grepl(".rds",file_names)]
    
    # Step 3: get the read.csv function working
    files = readRDS("1 .rds")
    
    # Step 4: use lapply to apply the read.csv function to all values of file_names
    files = lapply(file_names, readRDS)
    files = rbindlist(files, fill = TRUE)
    
    # check structure of new data set
    str(files)
    
    # rename
    PRICES = files
    
    # set directory
    setwd(dwfinrds)
    
    # Saving a single object to a file
    saveRDS(PRICES, "PRICES.rds")
    
    
  } # Join databases
  
  # Dropping unnecessary databases
  remove(list = c("files", "file_names"))
  
  # renaming database
  PRICES_Essay_II = PRICES %>% 
    group_by(year, month, air_arr, air_dep, airline) %>%
    dplyr::summarise(seat = sum(seat), revenue = sum(revenue))
 
  # set directory
  setwd(dwfinrds)
    
  # Saving a single object to a file
  saveRDS(PRICES_Essay_II, "PRICES_Essay_II.rds")

  
} # Transforming Prices database

{
  # set directory
  setwd(dwfinrds)
  
  # Importing databases
  BASICA =    readRDS("BASICA_Essay_II.rds")
  COMBINADA = readRDS("COMBINADA_Essay_II.rds")
  PRICES =    readRDS("PRICES_Essay_II.rds")
  
  # Merging databases
  BASE = BASICA %>% left_join(COMBINADA, 
                               by = c("id_empresa", "nr_voo", "hr_partida_real", 
                                      "dt_partida_real", "sg_icao_origem", "sg_icao_destino", 
                                      "hr_chegada_real", "dt_chegada_real")) %>%
    mutate(taxa = seat_com / seat_bas) %>%
    filter(taxa > 0 & taxa <= 1) %>%
    filter(id_di %in% c(2,3,6) & ds_natureza_etapa == "DOMÉSTICA")
  
  # Saving a single object to a file
  saveRDS(BASE, "BASE_Essay_II.rds")
  
  # organize database
  FINAL = BASE %>%
    group_by(sg_empresa_icao, sg_icao_origem, sg_icao_destino, nr_ano_mes_referencia) %>%
    dplyr::summarise(lt_fuel = sum(lt_combustivel),
                     seat_offer = sum(nr_assentos_ofertados),
                     payload_off = sum(kg_payload),
                     km_distance = sum(km_distancia),
                     seat_free = sum(nr_passag_gratis),
                     payload_dem = sum(kg_carga_paga),
                     mail = sum(kg_correio),
                     take_off = sum(nr_decolagem),
                     weight = sum(kg_peso),
                     nr_ask = sum(nr_ask),
                     nr_atk = sum(nr_atk),
                     nr_rpk = sum(nr_rpk),
                     nr_rtk = sum(nr_rtk), 
                     seat_com = sum(seat_com),
                     seat_bas = sum(seat_bas)) %>%
    mutate(taxa = seat_com / seat_bas) %>%
    filter(taxa > 0 & taxa <= 1) %>%
    mutate(air_dep = sg_icao_origem, air_arr = sg_icao_destino, airline = sg_empresa_icao)
  
  # create ANO and MES variables
  FINAL = FINAL %>% 
    mutate(year = as.double(str_sub(nr_ano_mes_referencia, 1, 4)),
           month = as.double(str_sub(nr_ano_mes_referencia, 5, 6)))
  
  # join databases
  FINAL = FINAL %>% left_join(PRICES, by = c("year", "month", "airline", "air_dep", "air_arr")) %>%
    filter(seat > 0) %>% 
    mutate(seat_dem = seat)
  
  # organizing database
  FINAL = FINAL %>% ungroup() %>%
    select("year", "month", "airline", "air_dep", "air_arr", 
           "seat_offer", "seat_bas", "seat_com", "seat_dem", "seat_free", "taxa",
           "take_off", "revenue", "payload_off", "payload_dem", "mail", "weight", 
           "lt_fuel", "km_distance", "nr_ask", "nr_atk", "nr_rpk", "nr_rtk") %>% 
    mutate(distance = km_distance/take_off)
  
  # Saving a single object to a file
  saveRDS(FINAL, "FINAL_Essay_II.rds")
  
} # Organizing databases

# Test of FINAL database length variables
LENGTH = FINAL %>% group_by(month, year) %>%
  dplyr::summarise(airline = length(airline), 
                   air_dep = length(air_dep), air_arr = length(air_arr),
                   seat_offer = length(seat_offer), seat_bas = length(seat_bas), 
                   seat_com = length(seat_com), seat_dem = length(seat_dem), 
                   seat_free = length(seat_free), taxa = length(taxa), take_off = length(take_off),
                   revenue = length(revenue), payload_off = length(payload_off), 
                   payload_dem = length(payload_dem), mail = length(mail), weight = length(weight),
                   lt_fuel = length(lt_fuel), km_distance = length(km_distance), 
                   nr_ask = length(nr_ask), nr_atk = length(nr_atk), nr_rpk = length(nr_rpk),
                   nr_rtk = length(nr_rtk))
                   
```

```{r organizing, include = FALSE}

{
  # setting the directory  
  setwd(dwfinrds)
  
  # Importing databases
  FINAL = readRDS("FINAL_Essay_II.rds")

  # calculating the number of companies per route
  NROUTE = FINAL %>% group_by(year, month, air_arr, air_dep) %>%
    dplyr::summarise(N = n())
    
  # inserting market structure information by airline category
  BASE1 = FINAL %>% 
    left_join(NROUTE, by = c("year", "month", "air_arr", "air_dep")) %>%
    ungroup() %>%
    arrange(year, month, air_arr, air_dep, desc(revenue)) %>%
    group_by(year, month, air_arr, air_dep) %>%
    dplyr::mutate(id = sequence(n())) %>%
    dplyr::mutate(market = case_when(id == 1 ~ "lider", TRUE ~ "seguidora"))
  
  ## Calculating route HHI
    
  # summarizing by route
  ARShare = BASE1 %>% group_by(year, month, air_arr, air_dep) %>% 
    dplyr::summarise(tfreq = sum(take_off),
                       tseat = sum(seat_bas)) 
    
  # calculating share and share^2
  BASE1 = BASE1 %>% left_join(ARShare, by = c("year", "month", "air_arr", "air_dep")) %>%
    mutate(FreqShare = take_off/tfreq, RouteShare = seat_bas/tseat) %>%
    mutate(FreqShare2 = FreqShare^2, RouteShare2 = RouteShare^2 )
    
  # calculating HHI by route
  HHIrs = BASE1 %>% group_by(year, month, air_arr, air_dep) %>% 
    dplyr::summarise(FreqHHI = sum(FreqShare2), RouteHHI = sum(RouteShare2))
    
  # merging all
  BASE1 = BASE1 %>% left_join(HHIrs, by = c("year", "month", "air_arr", "air_dep"))

  ## Calculating airport HHI (departure)
    
  # summarizing by departure airport and airline
  tca_seat = BASE1 %>% group_by(year, month, air_dep, airline) %>% 
    dplyr::summarise(tca_seat = sum(seat_bas)) 
    
  # summarizing by departure airport
  ta_seat = BASE1 %>% group_by(year, month, air_dep) %>% 
    dplyr::summarise(ta_seat = sum(seat_bas)) 
    
  # calculating share and share^2 
  tca_seat = tca_seat %>% left_join(ta_seat, by = c("year", "month", "air_dep")) %>%
    mutate(DepShare = tca_seat/ta_seat) %>%
    mutate(DepShare2 = DepShare^2)
    
  # calculating HHI by airport
  DepHHI = tca_seat %>% group_by(year, month, air_dep) %>% 
    dplyr::summarise(DepHHI = sum(DepShare2))
    
  # merging all
  tca_seat = tca_seat %>% left_join(DepHHI, by = c("year", "month", "air_dep")) 
    
  # merging HHI database with BASE1
  BASE1 = BASE1 %>% left_join(tca_seat, by = c("year", "month", "air_dep", "airline"))
    
  ## Calculating airport HHI (departure)
    
  # summarizing by arrival airport and airline
  tcd_seat = BASE1 %>% group_by(year, month, air_arr, airline) %>% 
    dplyr::summarise(tcd_seat = sum(seat_bas)) 
    
  # summarizing by arrival airport
  td_seat = BASE1 %>% group_by(year, month, air_arr) %>% 
    dplyr::summarise(td_seat = sum(seat_bas)) 
    
  # calculating share and share^2
  tcd_seat = tcd_seat %>% left_join(td_seat, by = c("year", "month", "air_arr")) %>%
    mutate(ArrShare = tcd_seat/td_seat) %>%
    mutate(ArrShare2 = ArrShare^2)
    
  # calculating HHI by airport
  ArrHHI = tcd_seat %>% group_by(year, month, air_arr) %>% 
    dplyr::summarise(ArrHHI = sum(ArrShare2))
    
  # merging all
  tcd_seat = tcd_seat %>% left_join(ArrHHI, by = c("year", "month", "air_arr")) %>%
    select(year, month, air_arr, airline, ArrShare, ArrHHI)
  
  # merging HHI database with BASE1
  BASE1 = BASE1 %>% left_join(tcd_seat, by = c("year", "month", "air_arr", "airline")) 
    
  ## inserting dummies
    
  # editing dummy for tourist airport
  BASE1 = BASE1 %>% mutate(Tourist = case_when(air_arr == "SBAR" ~ TRUE,
                                               air_arr == "SBCB" ~ TRUE,
                                               air_arr == "SBDB" ~ TRUE,
                                               air_arr == "SBFI" ~ TRUE,
                                               air_arr == "SBFN" ~ TRUE,
                                               air_arr == "SBFZ" ~ TRUE,
                                               air_arr == "SBGL" ~ TRUE,
                                               air_arr == "SBGV" ~ TRUE,
                                               air_arr == "SBIL" ~ TRUE,
                                               air_arr == "SBLE" ~ TRUE,
                                               air_arr == "SBPS" ~ TRUE,
                                               air_arr == "SBRF" ~ TRUE,
                                               air_arr == "SBVT" ~ TRUE,
                                               air_arr == "SBFL" ~ TRUE,
                                               TRUE ~ FALSE))
    
  # editing dummy for HUB airport
  BASE1 = BASE1 %>% mutate(ArrHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                              air_arr == "SBGL" ~ TRUE,
                                              air_arr == "SBRJ" ~ TRUE,
                                              air_arr == "SBGR" ~ TRUE,
                                              air_arr == "SBBR" ~ TRUE,
                                              air_arr == "SBFZ" ~ TRUE,
                                              air_arr == "SBRF" ~ TRUE,
                                              air_arr == "SBBH" ~ TRUE,
                                              air_arr == "SBKP" ~ TRUE,
                                              air_arr == "SBEG" ~ TRUE,
                                              TRUE ~ FALSE),
                           DepHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                              air_arr == "SBGL" ~ TRUE,
                                              air_arr == "SBRJ" ~ TRUE,
                                              air_arr == "SBGR" ~ TRUE,
                                              air_arr == "SBBR" ~ TRUE,
                                              air_arr == "SBFZ" ~ TRUE,
                                              air_arr == "SBRF" ~ TRUE,
                                              air_arr == "SBBH" ~ TRUE,
                                              air_arr == "SBKP" ~ TRUE,
                                              air_arr == "SBEG" ~ TRUE,
                                              TRUE ~ FALSE))
  
  # creating hubbling index and aircraft size
  BASE1 = BASE1 %>% mutate(hubling = 1-taxa,
                           aircraft = seat_offer/take_off)
    
  # creating seat and payload capacity index
  BASE1 = BASE1 %>% mutate(tx_seat = nr_rpk/nr_ask,
                           tx_payload = nr_rtk/nr_atk) %>%
    mutate(tx_seat = case_when(tx_seat < 0 ~ 0,
                               tx_seat > 1 ~ 1,
                               TRUE ~ tx_seat))
    
  # importing IPCA database
  IPCA = read_delim(url("https://raw.githubusercontent.com/jrtonin/thesis_data/main/data/parameter/IPCA.csv"), 
                    ";", escape_double = FALSE, 
                    locale = locale(decimal_mark = ",",
                                    grouping_mark = "."), 
                    trim_ws = TRUE) 
    
  # merge IPCA and BASE1 databases
    BASE1 = BASE1 %>% left_join(IPCA, by = c("year", "month")) %>%
    mutate(revenue = revenue*Index) %>%
    mutate(price = revenue/seat_dem)
    
  # creating BASE database
  BASE = BASE1
  
  # setting the directory  
  setwd(dwfinrds)
    
  # Saving a single object to a file
  saveRDS(BASE, "BASE_Essay_II.rds")
    
  # selecting final BASE1 database
  BASE1 = BASE1 %>% ungroup() %>% 
    select(year, month, air_dep, air_arr, airline,
           seat_offer, seat_com, seat_bas, seat_dem, seat_free,
           revenue, price, take_off, hubling, distance, lt_fuel,
           mail, weight, tx_seat, tx_payload, N, aircraft,
           RouteShare, FreqHHI, RouteHHI, DepHHI, ArrHHI,
           DepShare, ArrShare, FreqShare,
           Tourist, ArrHUB, DepHUB, market)
  
  # inserting arrival airport market structure by airline
  market_arr = BASE1 %>% 
    ungroup() %>%
    group_by(year, month, air_arr, airline) %>%
    dplyr::summarise(revenue = sum(revenue)) %>%
    arrange(year, month, air_arr, desc(revenue)) %>%
    group_by(year, month, air_arr) %>%
    dplyr::mutate(id = sequence(n())) %>%
    dplyr::mutate(market_arr = case_when(id == 1 ~ "lider", TRUE ~ "seguidora")) %>%
    select(-revenue, -id)
  
  # inserting departure airport market structure by airline
  market_dep = BASE1 %>% 
    ungroup() %>%
    group_by(year, month, air_dep, airline) %>%
    dplyr::summarise(revenue = sum(revenue)) %>%
    arrange(year, month, air_dep, desc(revenue)) %>%
    group_by(year, month, air_dep) %>%
    dplyr::mutate(id = sequence(n())) %>%
    dplyr::mutate(market_dep = case_when(id == 1 ~ "lider", TRUE ~ "seguidora")) %>%
    select(-revenue, -id)
  
  # merging database
  BASE1 = BASE1 %>%
    left_join(market_arr, by = c("year", "month", "air_arr", "airline")) %>%
    left_join(market_dep, by = c("year", "month", "air_dep", "airline")) %>%
    arrange(year, month, air_dep, air_arr, airline)
  
  # Saving a single object to a file
  saveRDS(BASE1, "BASE1_Essay_II.rds")
    
  # applying log
  LBASE1 = BASE1 %>% mutate(seat_offer = log(seat_offer), 
                            seat_com = log(seat_com), 
                            seat_bas = log(seat_bas), 
                            seat_dem = log(seat_dem), 
                            seat_free = log(seat_free),
                            revenue = log(revenue), 
                            price = log(price),
                            take_off = log(take_off), 
                            hubling = log(hubling), 
                            distance = log(distance), 
                            lt_fuel = log(lt_fuel),
                            mail = log(mail), 
                            weight = log(weight), 
                            tx_seat = log(1+tx_seat), 
                            tx_payload = log(1+tx_payload),
                            aircraft = log(aircraft),
                            RouteShare = log(RouteShare), 
                            FreqHHI = log(FreqHHI), 
                            RouteHHI = log(RouteHHI), 
                            DepHHI = log(DepHHI), 
                            ArrHHI = log(ArrHHI),
                            DepShare = log(DepShare),
                            ArrShare = log(ArrShare),
                            FreqShare = log(FreqShare))
    
  # transforming inf to 0
  is.na(LBASE1) = sapply(LBASE1, is.infinite)
  LBASE1[is.na(LBASE1)] = 0
    
  # Saving a single object to a file
  saveRDS(LBASE1, "LBASE1_Essay_II.rds")
  
} # Organizing BASE1 and LBASE1 databases

{
  # pre-organizing BASE2 database
  BASE2 = BASE %>% filter(N == 2) %>%
    group_by(year, month, air_dep, air_arr, market) %>% 
    dplyr::summarise(seat_offer = sum(seat_offer),
                     seat_com = sum(seat_com),
                     seat_bas = sum(seat_bas),
                     seat_dem = sum(seat_dem),
                     seat_free = sum(seat_free),
                     revenue = sum(revenue),
                     take_off = sum(take_off),
                     lt_fuel = sum(lt_fuel), 
                     mail = sum(mail),
                     weight =  sum(weight),
                     nr_ask =  sum(nr_ask),
                     nr_atk =  sum(nr_atk),
                     nr_rpk =  sum(nr_rpk),
                     nr_rtk =  sum(nr_rtk)) %>%
    mutate(price = revenue/seat_dem,
           tx_seat = nr_rpk/nr_ask,
           tx_payload = nr_rtk/nr_atk,
           hubling = seat_com / seat_bas,
           aircraft = seat_offer / take_off) 
    
  # filtering leader and follower companies
  lider = BASE2 %>% filter(market == "lider")
  seguidora = BASE2 %>% filter(market == "seguidora")
    
  # joining leader and follower companies with BASE2 database
  BASE2 = left_join(lider, seguidora, by = c("year", "month", "air_arr", "air_dep")) %>%
    mutate(CODE = paste0(air_arr, air_dep))
    
  # setting price and demand variables
  ROUTES = BASE2 %>% 
    mutate(seat_l = seat_dem.x, revenue_l = revenue.x,
           seat_f = seat_dem.y, revenue_f = revenue.y) %>%
    mutate(price_l = revenue_l/seat_l, price_f = revenue_f/seat_f) %>%
    mutate(seat_l = log(seat_l), seat_f = log(seat_f), 
           price_l = log(price_l), price_f = log(price_f)) %>%
    select(year, month, air_dep, air_arr, seat_l, 
           price_l, seat_f, price_f, CODE) %>%
    arrange(CODE, year, month)
    
  # calculating the difference of leader and follower companies data
  BASE2 = BASE2 %>% mutate(seat_offer = seat_offer.x - seat_offer.y,
                           seat_com = seat_com.x - seat_com.y,
                           seat_bas = seat_bas.x - seat_bas.y,
                           seat_dem = seat_dem.x - seat_dem.y,
                           seat_free = seat_free.x - seat_free.y, 
                           revenue = revenue.x - revenue.y,
                           take_off = take_off.x - take_off.y,
                           lt_fuel = lt_fuel.x - lt_fuel.y,
                           mail = mail.x - mail.y,
                           weight = weight.x - weight.y,
                           price = price.x - price.y,
                           tx_seat = tx_seat.x - tx_seat.y,
                           tx_payload = tx_payload.x - tx_payload.y,
                           hubling = hubling.x - hubling.y,
                           aircraft = aircraft.x - aircraft.y) %>%
    group_by(year, month, air_arr, air_dep) %>%
    select(year, month, air_dep, air_arr,
           seat_offer, seat_com, seat_bas, seat_dem, seat_free,
           revenue, price, weight, take_off, lt_fuel, mail, aircraft,
           tx_seat, tx_payload, hubling)
    
  # editing the CONTROL database (basic information of routes)
  CONTROL = BASE %>% group_by(year, month, air_arr, air_dep) %>% 
    dplyr::summarise(N = mean(N),
                     FreqHHI = mean(FreqHHI),
                     RouteHHI = mean(RouteHHI),
                     ArrHHI = mean(ArrHHI),
                     DepHHI = mean(DepHHI),
                     distance = mean(distance))
    
  # merging CONTROL and BASE2 databases
  BASE2 = BASE2 %>% left_join(CONTROL, by = c("year", "month", "air_dep", "air_arr"))
    
  # editing dummy of tourist airports 
  BASE2 = BASE2 %>% mutate(Tourist = case_when(air_dep == "SBAR" ~ TRUE,
                                              air_dep == "SBCB" ~ TRUE,
                                              air_dep == "SBDB" ~ TRUE,
                                              air_dep == "SBFI" ~ TRUE,
                                              air_dep == "SBFN" ~ TRUE,
                                              air_dep == "SBFZ" ~ TRUE,
                                              air_dep == "SBGL" ~ TRUE,
                                              air_dep == "SBGV" ~ TRUE,
                                              air_dep == "SBIL" ~ TRUE,
                                              air_dep == "SBLE" ~ TRUE,
                                              air_dep == "SBPS" ~ TRUE,
                                              air_dep == "SBRF" ~ TRUE,
                                              air_dep == "SBVT" ~ TRUE,
                                              air_dep == "SBFL" ~ TRUE,
                                              TRUE ~ FALSE))
  # editing dummy of HUB airports 
  BASE2 = BASE2 %>% mutate(ArrHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                              air_arr == "SBGL" ~ TRUE,
                                              air_arr == "SBRJ" ~ TRUE,
                                              air_arr == "SBGR" ~ TRUE,
                                              air_arr == "SBBR" ~ TRUE,
                                              air_arr == "SBFZ" ~ TRUE,
                                              air_arr == "SBRF" ~ TRUE,
                                              air_arr == "SBBH" ~ TRUE,
                                              air_arr == "SBKP" ~ TRUE,
                                              air_arr == "SBEG" ~ TRUE,
                                              TRUE ~ FALSE),
                           DepHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                              air_arr == "SBGL" ~ TRUE,
                                              air_arr == "SBRJ" ~ TRUE,
                                              air_arr == "SBGR" ~ TRUE,
                                              air_arr == "SBBR" ~ TRUE,
                                              air_arr == "SBFZ" ~ TRUE,
                                              air_arr == "SBRF" ~ TRUE,
                                              air_arr == "SBBH" ~ TRUE,
                                              air_arr == "SBKP" ~ TRUE,
                                              air_arr == "SBEG" ~ TRUE,
                                              TRUE ~ FALSE))
    
  # summarizing BASE2 and applying log 
  LBASE2 = BASE %>% filter(N == 2) %>%
    group_by(year, month, air_dep, air_arr, market) %>% 
    dplyr::summarise(seat_offer = sum(seat_offer),
                     seat_com = sum(seat_com),
                     seat_bas = sum(seat_bas),
                     seat_dem = sum(seat_dem),
                     seat_free = sum(seat_free),
                     revenue = sum(revenue),
                     take_off = sum(take_off),
                     lt_fuel = sum(lt_fuel), 
                     mail = sum(mail),
                     weight =  sum(weight),
                     nr_ask =  sum(nr_ask)+1,
                     nr_atk =  sum(nr_atk)+1,
                     nr_rpk =  sum(nr_rpk)+1,
                     nr_rtk =  sum(nr_rtk)+1) %>%
    mutate(seat_offer = log(seat_offer),
           seat_com = log(seat_com),
           seat_bas = log(seat_bas),
           seat_dem = log(seat_dem),
           revenue = log(revenue),
           take_off = log(take_off),
           lt_fuel = log(lt_fuel), 
           mail = log(mail),
           weight =  log(weight),
           nr_ask =  log(nr_ask),
           nr_atk =  log(nr_atk),
           nr_rpk =  log(nr_rpk),
           nr_rtk =  log(nr_rtk),
           price = log(revenue/seat_dem),
           tx_seat = log(1+(nr_rpk/nr_ask)),
           tx_payload = log(1+(nr_rtk/nr_atk)),
           hubling = log(seat_com / seat_bas),
           aircraft = log(seat_offer/take_off))
  
  # transforming inf data in 0
  is.na(LBASE2) = sapply(LBASE2, is.infinite)
  LBASE2[is.na(LBASE2)] = 0
    
  # filtering leader and follower companies
  lider = LBASE2 %>% filter(market == "lider")
  seguidora = LBASE2 %>% filter(market == "seguidora")
    
  # merging leader and follower database with LBASE2
  LBASE2 = left_join(lider, seguidora, by = c("year", "month", "air_arr", "air_dep")) 
    
  # calculating the difference of leader and follower companies in database
  LBASE2 = LBASE2 %>% mutate(seat_offer = seat_offer.x - seat_offer.y,
                             seat_com = seat_com.x - seat_com.y,
                             seat_bas = seat_bas.x - seat_bas.y,
                             seat_dem = seat_dem.x - seat_dem.y,
                             revenue = revenue.x - revenue.y,
                             take_off = take_off.x - take_off.y,
                             lt_fuel = lt_fuel.x - lt_fuel.y, 
                             mail = mail.x - mail.y,
                             weight = weight.x - weight.y,
                             price = price.x - price.y,
                             tx_seat = tx_seat.x - tx_seat.y,
                             tx_payload = tx_payload.x - tx_payload.y,
                             hubling = hubling.x - hubling.y,
                             aircraft = aircraft.x - aircraft.y) %>%
    group_by(year, month, air_arr, air_dep) %>%
    select(year, month, air_dep, air_arr,
           seat_offer, seat_com, seat_bas, seat_dem, revenue, aircraft,
           take_off, lt_fuel, mail, weight, price, tx_seat, tx_payload, hubling)
  
  # editing the CONTROL database (basic information of routes)
  CONTROL = BASE %>% group_by(year, month, air_arr, air_dep) %>% 
      dplyr::summarise(N = mean(N),
                     FreqHHI = log(mean(FreqHHI)),
                     RouteHHI = log(mean(RouteHHI)),
                     ArrHHI = log(mean(ArrHHI)),
                     DepHHI = log(mean(DepHHI)),
                     distance = log(mean(distance)))
    
  # merging CONTROL and LBASE2 databases
  LBASE2 = LBASE2 %>% left_join(CONTROL, by = c("year", "month", "air_dep", "air_arr"))
    
  # editing dummy of tourist airports 
  LBASE2 = LBASE2 %>% mutate(Tourist = case_when(air_dep == "SBAR" ~ TRUE,
                                                air_dep == "SBCB" ~ TRUE,
                                                air_dep == "SBDB" ~ TRUE,
                                                air_dep == "SBFI" ~ TRUE,
                                                air_dep == "SBFN" ~ TRUE,
                                                air_dep == "SBFZ" ~ TRUE,
                                                air_dep == "SBGL" ~ TRUE,
                                                air_dep == "SBGV" ~ TRUE,
                                                air_dep == "SBIL" ~ TRUE,
                                                air_dep == "SBLE" ~ TRUE,
                                                air_dep == "SBPS" ~ TRUE,
                                                air_dep == "SBRF" ~ TRUE,
                                                air_dep == "SBVT" ~ TRUE,
                                                air_dep == "SBFL" ~ TRUE,
                                                TRUE ~ FALSE))
  # editing dummy of HUB airports 
  LBASE2 = LBASE2 %>% mutate(ArrHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                                air_arr == "SBGL" ~ TRUE,
                                                air_arr == "SBRJ" ~ TRUE,
                                                air_arr == "SBGR" ~ TRUE,
                                                air_arr == "SBBR" ~ TRUE,
                                                air_arr == "SBFZ" ~ TRUE,
                                                air_arr == "SBRF" ~ TRUE,
                                                air_arr == "SBBH" ~ TRUE,
                                                air_arr == "SBKP" ~ TRUE,
                                                air_arr == "SBEG" ~ TRUE,
                                                TRUE ~ FALSE),
                             DepHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                                air_arr == "SBGL" ~ TRUE,
                                                air_arr == "SBRJ" ~ TRUE,
                                                air_arr == "SBGR" ~ TRUE,
                                                air_arr == "SBBR" ~ TRUE,
                                                air_arr == "SBFZ" ~ TRUE,
                                                air_arr == "SBRF" ~ TRUE,
                                                air_arr == "SBBH" ~ TRUE,
                                                air_arr == "SBKP" ~ TRUE,
                                                air_arr == "SBEG" ~ TRUE,
                                                TRUE ~ FALSE)) %>%
    mutate(CODE = paste0(air_arr,air_dep))
  
  
  # setting the directory  
  setwd(dwfinrds)
  
  # Saving a single object to a file
  saveRDS(BASE2, "BASE2_Essay_II.rds")
  saveRDS(LBASE2, "LBASE2_Essay_II.rds")    
    
} # organizing BASE2 and LBASE2 databases

```

```{r HAUSMAN_instruments_I, include=FALSE}

# organizing database
ROUTES = BASE1 %>%
  group_by(air_arr, air_dep) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::select(-n)

# importing aerodromo database
aerodromos = read_delim("C:/TESE/OUTROS/aerodromos.csv", 
                        delim = ";", escape_double = FALSE, 
                        locale = locale(encoding = "ISO-8859-1"), 
                        trim_ws = TRUE)

# importing lat and lon by city
urlfile = "https://raw.githubusercontent.com/kelvins/Municipios-Brasileiros/main/csv/municipios.csv"
latlon = read_csv(url(urlfile)) %>%
  mutate(code_city = codigo_ibge,
         lat = latitude,
         lon = longitude,
         city = nome,
         uf_code = codigo_uf) %>% 
  dplyr::select(code_city, city, uf_code, lat, lon)

# including IBGE code and lat and lon
aerodromos = aerodromos %>%
  left_join(latlon, by = c("city", "uf_code")) 


# summarizing end points
endpointa = ROUTES %>% 
  group_by(air_dep) %>% 
  dplyr::summarise(n = n()) %>% 
  dplyr::select(-n) %>%
  left_join(aerodromos %>% dplyr::select(code, code_city), 
            by = c("air_dep" = "code")) %>%
  group_by(code_city) %>%
  dplyr::summarise(n = n()) %>% 
  ungroup() %>%
  dplyr::select(-n)

# summarizing pre points
endpointb = ROUTES %>% 
  group_by(air_arr) %>% 
  dplyr::summarise(n = n()) %>% 
  dplyr::select(-n) %>%
  left_join(aerodromos %>% dplyr::select(code, code_city), by = c("air_arr" = "code")) %>%
  group_by(code_city) %>%
  dplyr::summarise(n = n()) %>% 
  ungroup() %>%
  dplyr::select(-n)

# edditing final endpoint database
endpoint = endpointa %>% bind_rows(endpointb) %>%
  group_by(code_city) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::select(-n)

# transforming endpoint to vector
vendpoint = as.vector(endpoint$code_city)

# combining endpoints
DISTANCES = as.data.frame(t(as.matrix(combn(vendpoint, 2)))) %>%
  filter(!is.na(V1) | !is.na(V2)) %>%
  mutate(filter = case_when(V1 == V2 ~ TRUE, TRUE ~ FALSE)) %>%
  filter(filter == FALSE) %>%
  left_join(aerodromos %>% select(code_city, lat, lon), by = c("V1" = "code_city")) %>%
  mutate(lat_arr = lat, lon_arr = lon, arr = V1, dep = V2) %>%
  select(arr, dep, lat_arr, lon_arr) %>%
  left_join(aerodromos %>% select(code_city, lat, lon), by = c("dep" = "code_city")) %>%
  mutate(lat_dep = lat, lon_dep = lon) %>%
  select(arr, lat_arr, lon_arr, dep, lat_dep, lon_dep) %>%
  rowwise() %>%
  dplyr::mutate(distance = distm(x = c(lon_arr, lat_arr), 
                                 y = c(lon_dep, lat_dep), 
                                 fun = distHaversine)/1000) %>%
  distinct() %>%
  mutate(distance = round(distance, 0)) 

# generating final DISTANCES database
DISTANCES = DISTANCES %>% 
  mutate(air_dep = dep, air_arr = arr) %>% 
  select(air_arr, air_dep, distance) %>%
  bind_rows(DISTANCES %>% 
              mutate(air_dep = arr, air_arr = dep) %>% 
              select(air_arr, air_dep, distance))

# generating pre database
BASEF = BASE1 %>% 
  mutate(id = sequence(n()),
         yearmonth = paste0(year, month)) %>%
  select(air_dep, air_arr, airline, DepHHI, id, yearmonth) %>%
  ungroup() %>%
  left_join(aerodromos %>% select(code, code_city), by = c("air_dep" = "code")) %>%
  mutate(dep_code_city = code_city) %>% select(-code_city) %>%
  left_join(aerodromos %>% select(code, code_city), by = c("air_arr" = "code")) %>%
  mutate(arr_code_city = code_city) %>% select(-code_city)  

# creating id vector
id = as.vector(BASEF$id)

# editing looping 
for (file in 1:22810){ 

  # filtering airline variable
  cia = BASEF %>% filter(id == id[file])
  cia = as.vector(cia$airline)
  
  # filtering time variable
  ym = BASEF %>% filter(id == id[file])
  ym = as.vector(ym$yearmonth) 
  
  # filtering airport variable
  airport = BASEF %>% filter(id == id[file])
  airport = as.vector(airport$arr_code_city)
  
  # filtering airline and time in BASEF database
  BASE = BASEF %>% filter(airline %in% cia & yearmonth %in% ym)
  
  # filtering airports with distances greater than 150 km to arrival airport
  distance150 = DISTANCES %>% filter(air_arr %in% airport & distance > 150)
  airportarr = as.vector(distance150$air_dep) 
  
  # summarizing DepHHI mean of routes
  distance150 = BASE %>% filter(arr_code_city %in% airportarr) %>%
    dplyr::summarise(mDepHHI150 = mean(DepHHI))
  
  # consolidating information
  distance150 = as.vector(distance150$mDepHHI150)
  
  
  # filtering airports with distances greater than 300 km to arrival airport
  distance300 = DISTANCES %>% filter(air_arr %in% airport & distance > 300)
  airportarr = as.vector(distance300$air_dep) 
  
  # summarizing DepHHI mean of routes
  distance300 = BASE %>% filter(arr_code_city %in% airportarr) %>%
    dplyr::summarise(mDepHHI300 = mean(DepHHI))
  
  # consolidating information
  distance300 = as.vector(distance300$mDepHHI300)
  
  
  # filtering airports with distances greater than 500 km to arrival airport
  distance500 = DISTANCES %>% filter(air_arr %in% airport & distance > 500)
  airportarr = as.vector(distance500$air_dep) 
  
  # summarizing DepHHI mean of routes
  distance500 = BASE %>% filter(arr_code_city %in% airportarr) %>%
    dplyr::summarise(mDepHHI500 = mean(DepHHI))
  
  # consolidating information
  distance500 = as.vector(distance500$mDepHHI500)
  
  # criating final database
  final = matrix(c(id[file], distance150, distance300, distance500), nrow = 1)
  final = as.data.frame(final)
  colnames(final) = c("id", "DepHHI150", "DepHHI300", "DepHHI500")
  
  # setting the directory      
  setwd("C:/TESE/INSTRUMENT/INSTRUMENT_RDS") 
    
  # Saving a single object to a file
  saveRDS(final, paste(file, ".rds"))
  
  } # Creating looping

```