---
title: "Brazilian airline market data cleaning"
author: "João Ricardo Tonin"
date: "31/10/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, 
                      comment = NA,
                      warning = FALSE,
                      error = FALSE, 
                      message = FALSE,
                      tidy = TRUE)

print(getwd())
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
dwdir = print(getwd())

{ 
  # Check if the packages that we need are installed
  want = c("tidyverse", "plm", "texreg", "lmtest", "knitr", "data.table",
           "geosphere", "rprojroot")
  have = want %in% rownames(installed.packages())
  # Install the packages that we miss
  if ( any(!have) ) { install.packages( want[!have] ) }
  # Load the packages
  junk <- lapply(want, library, character.only = T)
  # Remove the objects we created
  rm(have, want, junk)
} # Import packages

# setting directories
dwcomraw = paste0(dwdir, "/data/combined/raw")
dwcomrds = paste0(dwdir, "/data/combined/rds")
dwfinrds = paste0(dwdir, "/data/final")
dwbasraw = paste0(dwdir, "/data/basic/raw")
dwbasrds = paste0(dwdir, "/data/basic/rds")
dwpriraw = paste0(dwdir, "/data/prices/raw")
dwprirds = paste0(dwdir, "/data/prices/rds")
dwhaurds = paste0(dwdir, "/data/instrument/hausman/rds")
dwestraw = paste0(dwdir, "/data/instrument/estban/raw")
dwestrds = paste0(dwdir, "/data/instrument/estban/rds")

# define memory limit
memory.limit(size = 999999999999)

```

```{r cleanning, include = FALSE}

{
  # setting the directory  
  setwd(dwcomraw) 
  
  # creating a list of .CSV databases
  temp = list.files(pattern = "*.txt") 
  
  for (file in 1:36){ 

    # setting the directory    
    setwd(dwcomraw) 
    
    # get the read_delim function working
    vfiles = read_delim(temp[file], ";", 
                        escape_double = FALSE,
                        col_types = cols(cd_di = col_character(), 
                                         ds_cotran = col_character(),
                                         cd_cotran = col_character()),  
                        locale = locale(decimal_mark = ",", 
                                        grouping_mark = ".", 
                                        encoding = "ISO-8859-1"), 
                        trim_ws = TRUE)
    
    # organizing database
    COMBINADA = vfiles %>% 
      mutate(seat_com = nr_passag_pagos) %>% ungroup() %>%
      select("id_empresa", "nr_voo", "hr_partida_real", "dt_partida_real", 
             "sg_icao_origem", "sg_icao_destino", "hr_chegada_real", "dt_chegada_real",
             "seat_com", "cd_cotran", "ds_cotran","nr_ano_mes_partida_real")
      
    # setting the directory      
    setwd(dwcomrds) 
    
    # Saving a single object to a file
    saveRDS(COMBINADA, paste(file, ".rds"))
 
  } # Creating looping for .txt files
  
  {
    # Step 1: set the working directory (where files are saved)
    setwd(dwcomrds) 
    
    # Step 2: get all the right file names
    file_names = list.files(getwd())
    file_names = file_names[grepl(".rds",file_names)]
    
    # Step 3: get the read.csv function working
    files = readRDS("1 .rds")
    
    # Step 4: use lapply to apply the read.csv function to all values of file_names
    files = lapply(file_names, readRDS)
    files = rbindlist(files, fill = TRUE)
    
    # check structure of new data set
    str(files)
    
    # rename
    COMBINADA = files
    
    
  } # Join databases
  
  # Dropping unnecessary databases
  remove(list = c("files", "file_names"))
  
  # transform NA to 0
  COMBINADA$seat_com[is.na(COMBINADA$seat_com)] = 0
  
  COMBINADA = COMBINADA %>% group_by(id_empresa, nr_voo, hr_partida_real, dt_partida_real,
                                 sg_icao_origem, sg_icao_destino, hr_chegada_real, 
                                 dt_chegada_real, ds_cotran, cd_cotran,
                                 nr_ano_mes_partida_real) %>%
    dplyr::summarise(seat_com = sum(seat_com))
  
  # setting the directory  
  setwd(dwfinrds)
  
  # Saving a single object to a file
  saveRDS(COMBINADA, "COMBINADA_Essay_II.rds")
  
} # Transforming Combinated database

{
  # setting the directory  
  setwd(dwbasraw) 
  
  # creating a list of .CSV databases
  temp = list.files(pattern = "*.txt") 
  
  for (file in 1:36){ 
    
    # setting the directory    
    setwd(dwbasraw) 
    
    # get the read_delim function working
    vfiles = read_delim(temp[file], ";", 
                        escape_double = FALSE,
                        col_types = cols(id_empresa = col_character(),
                                         cd_di = col_character(),
                                         lt_combustivel = col_double(),
                                         nr_assentos_ofertados = col_double(),
                                         kg_payload = col_double(), 
                                         km_distancia = col_double(),  
                                         nr_passag_gratis = col_double(), 
                                         kg_bagagem_livre = col_double(), 
                                         kg_bagagem_excesso = col_double(),
                                         kg_carga_paga = col_double(), 
                                         kg_carga_gratis = col_double(),
                                         kg_correio = col_double(), 
                                         nr_decolagem = col_double(), 
                                         nr_horas_voadas = col_double(), 
                                         kg_peso = col_double(), 
                                         nr_ask = col_double(), 
                                         nr_rpk = col_double(), 
                                         nr_atk = col_double(), 
                                         nr_rtk = col_double()),
                        locale = locale(decimal_mark = ",", 
                                        grouping_mark = ".", 
                                        encoding = "ISO-8859-1"), 
                        trim_ws = TRUE)
    
    # organizing database
    BASICA = vfiles %>% 
      mutate(seat_bas = nr_passag_pagos) %>% ungroup() %>%
      select("id_empresa", "nr_voo", "hr_partida_real", "dt_partida_real", 
             "sg_icao_origem", "sg_icao_destino", "hr_chegada_real", "dt_chegada_real", 
             "sg_empresa_icao", "id_di", "ds_di", 
             "ds_grupo_di", "nr_ano_referencia", "nr_ano_mes_referencia", 
             "ds_tipo_linha", "ds_natureza_etapa", "lt_combustivel", "nr_assentos_ofertados",
             "kg_payload", "km_distancia", "seat_bas", "nr_passag_gratis", 
             "kg_bagagem_livre", "kg_bagagem_excesso","kg_carga_paga", "kg_carga_gratis",
             "kg_correio", "nr_decolagem", "nr_horas_voadas", "kg_peso", 
             "nr_ask", "nr_rpk", "nr_atk", "nr_rtk")

    
    # setting the directory      
    setwd(dwbasrds) 
    
    # Saving a single object to a file
    saveRDS(BASICA, paste(file, ".rds"))
    
  } # Creating looping for .txt files
  
  {
    
    # Step 1: set the working directory (where files are saved)
    setwd(dwbasrds) 
    
    # Step 2: get all the right file names
    file_names = list.files(getwd())
    file_names = file_names[grepl(".rds",file_names)]
    
    # Step 3: get the read.csv function working
    files = readRDS("1 .rds")
    
    # Step 4: use lapply to apply the read.csv function to all values of file_names
    files = lapply(file_names, readRDS)
    files = rbindlist(files, fill = TRUE)
    
    # check structure of new data set
    str(files)
    
    # rename
    BASICA = files
    
    
  } # Join databases
  
  # Dropping unnecessary databases
  remove(list = c("files", "file_names"))
  
  # organizing database
  BASICA = BASICA %>% mutate_at(c(17:34), ~replace(., is.na(.), 0)) %>% ungroup() %>%
    group_by(id_empresa, nr_voo, hr_partida_real, dt_partida_real, sg_icao_origem,
             sg_icao_destino, hr_chegada_real, dt_chegada_real, sg_empresa_icao,
             id_di, ds_di, ds_grupo_di, nr_ano_referencia, nr_ano_mes_referencia,
             ds_tipo_linha, ds_natureza_etapa) %>%
    dplyr::summarise(lt_combustivel = sum(lt_combustivel),
                     nr_assentos_ofertados = sum(nr_assentos_ofertados), 
                     kg_payload = sum(kg_payload), 
                     km_distancia = sum(km_distancia),
                     seat_bas = sum(seat_bas), 
                     nr_passag_gratis = sum(nr_passag_gratis), 
                     kg_bagagem_livre = sum(kg_bagagem_livre), 
                     kg_bagagem_excesso = sum(kg_bagagem_excesso),
                     kg_carga_paga = sum(kg_carga_paga), 
                     kg_carga_gratis = sum(kg_carga_gratis),
                     kg_correio = sum(kg_correio), 
                     nr_decolagem = sum(nr_decolagem),
                     nr_horas_voadas = sum(nr_horas_voadas), 
                     kg_peso = sum(kg_peso),
                     nr_ask = sum(nr_ask), 
                     nr_rpk = sum(nr_rpk),
                     nr_atk = sum(nr_atk), 
                     nr_rtk = sum(nr_rtk))
  
  # setting the directory  
  setwd(dwfinrds) 
  
  # Saving a single object to a file
  saveRDS(BASICA, "BASICA_Essay_II.rds")
  
} # Transforming Basic database

{
  # setting the directory  
  setwd(dwpriraw) 
  
  # creating a list of .CSV databases
  temp = list.files(pattern = "*.CSV") 
  
  for (file in 1:35){ 
    
    # setting the directory    
    setwd(dwpriraw) 
    
    # get the read_delim function working
    vfiles = read_delim(temp[file], ";", 
                        escape_double = FALSE, 
                        locale = locale(decimal_mark = ",", grouping_mark = "."), 
                        trim_ws = TRUE)
    
    # organizing database
    PRECOS = vfiles %>% mutate(RECEITA = ASSENTOS*TARIFA) %>% 
      group_by(ANO, MES, EMPRESA, ORIGEM, DESTINO) %>%
      dplyr::summarise(ASSENTOS = sum(ASSENTOS),
                       RECEITA = sum(RECEITA))
    
    # Change the names of the columns
    names(PRECOS)[names(PRECOS) == "ASSENTOS"] = "seat"
    names(PRECOS)[names(PRECOS) == "RECEITA"] = "revenue"
    names(PRECOS)[names(PRECOS) == "EMPRESA"] = "airline"
    names(PRECOS)[names(PRECOS) == "ANO"] = "year"
    names(PRECOS)[names(PRECOS) == "MES"] = "month"
    names(PRECOS)[names(PRECOS) == "ORIGEM"] = "air_dep"
    names(PRECOS)[names(PRECOS) == "DESTINO"] = "air_arr"
    
    # setting the directory      
    setwd(dwprirds) 
    
    # Saving a single object to a file
    saveRDS(PRECOS, paste(file, ".rds"))
    
  } # Creating looping for .txt files
  
  {
    
    # Step 1: set the working directory (where files are saved)
    setwd(dwprirds) 
    
    # Step 2: get all the right file names
    file_names = list.files(getwd())
    file_names = file_names[grepl(".rds",file_names)]
    
    # Step 3: get the read.csv function working
    files = readRDS("1 .rds")
    
    # Step 4: use lapply to apply the read.csv function to all values of file_names
    files = lapply(file_names, readRDS)
    files = rbindlist(files, fill = TRUE)
    
    # check structure of new data set
    str(files)
    
    # rename
    PRICES = files
    
  } # Join databases
  
  # Dropping unnecessary databases
  remove(list = c("files", "file_names"))
  
  # renaming database
  PRICES = PRICES %>% 
    group_by(year, month, air_arr, air_dep, airline) %>%
    dplyr::summarise(seat = sum(seat), revenue = sum(revenue))
  
  # setting the directory  
  setwd(dwfinrds)

  # Saving a single object to a file
  saveRDS(PRICES, "PRICES_Essay_II.rds")

  } # Transforming Prices database

{
  
  # setting the directory
  setwd(dwfinrds)
  
  # import databases
  BASICA = readRDS("BASICA_Essay_II.rds") %>% 
    mutate(id_empresa = as.double(id_empresa))
  COMBINADA = readRDS("COMBINADA_Essay_II.rds") %>%
    filter(ds_cotran == "DESEMBARQUE") %>%
    mutate(id_empresa = as.double(id_empresa)) 
  PRICES = readRDS("PRICES_Essay_II.rds")
  
  # Merging databases
  BASE = BASICA %>% 
    mutate(nr_voo = as.double(nr_voo)) %>%
    left_join(COMBINADA %>% mutate(nr_voo = as.double(nr_voo)), 
                               by = c("id_empresa", "nr_voo", "hr_partida_real", 
                                      "dt_partida_real", "sg_icao_origem", "sg_icao_destino", 
                                      "hr_chegada_real", "dt_chegada_real")) %>%
    mutate(taxa = seat_com / seat_bas) %>%
    mutate(taxa = case_when(taxa < 0 ~ 0,
                            taxa > 1 ~ 1,
                            TRUE ~ taxa)) %>%
    filter(id_di %in% c(2,3,6) & ds_natureza_etapa == "DOMÉSTICA")
  
  # setting the directory  
  setwd(dwfinrds)  
  
  # Saving a single object to a file
  saveRDS(BASE, "BASE_Essay_II.rds")
  
  # organize database
  FINAL = BASE %>%
    group_by(sg_empresa_icao, sg_icao_origem, sg_icao_destino, nr_ano_mes_referencia) %>%
    dplyr::summarise(lt_fuel = sum(lt_combustivel),
                     seat_offer = sum(nr_assentos_ofertados),
                     payload_off = sum(kg_payload),
                     km_distance = sum(km_distancia),
                     seat_free = sum(nr_passag_gratis),
                     payload_dem = sum(kg_carga_paga),
                     mail = sum(kg_correio),
                     free_luggage = sum(kg_bagagem_livre),
                     paid_luggage = sum(kg_bagagem_excesso),
                     take_off = sum(nr_decolagem),
                     weight = sum(kg_peso),
                     nr_ask = sum(nr_ask),
                     nr_atk = sum(nr_atk),
                     nr_rpk = sum(nr_rpk),
                     nr_rtk = sum(nr_rtk), 
                     seat_com = sum(seat_com),
                     seat_bas = sum(seat_bas),
                     flight_hours = sum(nr_horas_voadas)) %>%
    mutate(taxa = seat_com / seat_bas) %>%
    mutate(taxa = case_when(taxa < 0 ~ 0,
                            taxa > 1 ~ 1,
                            TRUE ~ taxa)) %>%
    mutate(air_dep = sg_icao_origem, air_arr = sg_icao_destino, airline = sg_empresa_icao)
  
  # create ANO and MES variables
  FINAL = FINAL %>% 
    mutate(year = as.double(str_sub(nr_ano_mes_referencia, 1, 4)),
           month = as.double(str_sub(nr_ano_mes_referencia, 5, 6)))
  
  # join databases
  FINAL = FINAL %>% left_join(PRICES, by = c("year", "month", "airline", 
                                             "air_dep", "air_arr")) %>% 
    filter(seat > 0) %>% 
    mutate(seat_dem = seat)
  
  # organizing database
  FINAL = FINAL %>% ungroup() %>%
    select("year", "month", "airline", "air_dep", "air_arr", 
           "seat_offer", "seat_bas", "seat_com", "seat_dem", "seat_free", "taxa",
           "take_off", "revenue", "payload_off", "payload_dem", "mail", "weight", 
           "free_luggage", "paid_luggage", "lt_fuel", "km_distance", "flight_hours", 
           "nr_ask", "nr_atk", "nr_rpk", "nr_rtk") %>% 
    mutate(distance = km_distance/take_off)
  
  # setting the directory  
  setwd(dwfinrds) 
  
  # Saving a single object to a file
  saveRDS(FINAL, "FINAL_Essay_II.rds")
  
  # organizing BASE by schedulles
  BASE = BASE %>% mutate(hour = hour(hr_partida_real)) %>%
      mutate(schedule = case_when(hour %in% c(0,1,2,3,4,5) ~ "0-5",
                                  hour %in% c(6,7,8,9,10,11) ~ "6-11",
                                  hour %in% c(12,13,14,15,16,17) ~ "12-17",
                                  hour %in% c(18,19,20,21,22,23) ~ "18-23",
                                  TRUE ~ "Erro")) %>%
      group_by(nr_ano_referencia, nr_ano_mes_referencia, sg_empresa_icao, 
               sg_icao_origem, sg_icao_destino, schedule) %>%
      dplyr::summarise(takeoff = sum(nr_decolagem)) %>%
      group_by(nr_ano_referencia, nr_ano_mes_referencia, sg_empresa_icao, 
               sg_icao_origem, sg_icao_destino) %>%
      mutate(takeoff_total = sum(takeoff)) %>%
      mutate(part = takeoff/takeoff_total) %>% ungroup() %>%
      select(nr_ano_mes_referencia, sg_empresa_icao,
             sg_icao_origem, sg_icao_destino, schedule, part) %>%
      spread(schedule, part)
    
    # Change the names of the columns
    names(BASE)[names(BASE) == "nr_ano_mes_referencia"] = "data"
    names(BASE)[names(BASE) == "sg_empresa_icao"] = "airline"
    names(BASE)[names(BASE) == "sg_icao_origem"] = "air_dep"
    names(BASE)[names(BASE) == "sg_icao_destino"] = "air_arr"

    # replacing NA's
    HOUR = BASE %>% mutate_at(c(5:8), ~replace(., is.na(.), 0)) %>%
      mutate(year = as.double(str_sub(data, 1, 4)),
             month = as.double(str_sub(data, 5, 6))) %>%
      select(month, year, airline, air_dep, air_arr, `0-5`, `6-11`, `12-17`, `18-23`)
    
    # setting the directory  
    setwd(dwfinrds) 

    # saving database
    saveRDS(HOUR, "HOUR_Essay_II.rds")
  
} # Organizing databases 

```

```{r organizing, include = FALSE}

{
  {
    # setting the local directory
    setwd(dwfinrds)
    
    # reading FINAL database
    FINAL = readRDS("FINAL_Essay_II.rds")
    
    # creating CODE variable (joining air+dep airport code)
    FINAL = FINAL %>% mutate(CODE = paste0(air_arr, air_dep))
    
    # creating seat_fuel and payload_fuel
    FINAL = FINAL %>% mutate(seat_fuel = (lt_fuel/nr_rpk), 
                             payload_fuel = (lt_fuel/nr_rtk))
    
  } # importing FINAL database
  
  { 
    # calculating the number of companies per route
    NROUTE = FINAL %>% group_by(year, month, air_arr, air_dep) %>%
      dplyr::summarise(N = n())
    
    # inserting market structure information by airline category
    BASE1 = FINAL %>% 
      left_join(NROUTE, by = c("year", "month", "air_arr", "air_dep")) %>%
      #filter(N == 2) %>%
      ungroup() %>%
      arrange(year, month, air_arr, air_dep, desc(seat_bas)) %>%
      group_by(year, month, air_arr, air_dep) %>%
      dplyr::mutate(id = sequence(n())) %>%
      dplyr::mutate(market = case_when(id == 1 ~ "lider", TRUE ~ "seguidora"))
    
    ## Calculating route HHI
    
    # summarizing by route
    ARShare = BASE1 %>% group_by(year, month, air_arr, air_dep) %>% 
      dplyr::summarise(tfreq = sum(take_off),
                       tseat = sum(seat_bas)) 
    
    # calculating share and share^2
    BASE1 = BASE1 %>% left_join(ARShare, by = c("year", "month", "air_arr", "air_dep")) %>%
      mutate(FreqShare = take_off/tfreq, RouteShare = seat_bas/tseat) %>%
      mutate(FreqShare2 = FreqShare^2, RouteShare2 = RouteShare^2 )
    
    # calculating HHI by route
    HHIrs = BASE1 %>% group_by(year, month, air_arr, air_dep) %>% 
      dplyr::summarise(FreqHHI = sum(FreqShare2), RouteHHI = sum(RouteShare2))
    
    # merging all
    BASE1 = BASE1 %>% left_join(HHIrs, by = c("year", "month", "air_arr", "air_dep"))

    ## Calculating airport HHI (departure)
    
    # summarizing by departure airport and airline
    tca_seat = BASE1 %>% group_by(year, month, air_dep, airline) %>% 
      dplyr::summarise(tca_seat = sum(seat_bas)) 
    
    # summarizing by departure airport
    ta_seat = BASE1 %>% group_by(year, month, air_dep) %>% 
      dplyr::summarise(ta_seat = sum(seat_bas)) 
    
    # calculating share and share^2 
    tca_seat = tca_seat %>% left_join(ta_seat, by = c("year", "month", "air_dep")) %>%
      mutate(DepShare = tca_seat/ta_seat) %>%
      mutate(DepShare2 = DepShare^2)
    
    # calculating HHI by airport
    DepHHI = tca_seat %>% group_by(year, month, air_dep) %>% 
      dplyr::summarise(DepHHI = sum(DepShare2))
    
    # merging all
    tca_seat = tca_seat %>% left_join(DepHHI, by = c("year", "month", "air_dep")) 
    
    # merging HHI database with BASE1
    BASE1 = BASE1 %>% left_join(tca_seat, by = c("year", "month", "air_dep", "airline"))
    
    ## Calculating airport HHI (departure)
    
    # summarizing by arrival airport and airline
    tcd_seat = BASE1 %>% 
        group_by(year, month, air_arr, airline) %>% 
      dplyr::summarise(tcd_seat = sum(seat_bas)) 
    
    # summarizing by arrival airport
    td_seat = BASE1 %>% group_by(year, month, air_arr) %>% 
      dplyr::summarise(td_seat = sum(seat_bas)) 
    
    # calculating share and share^2
    tcd_seat = tcd_seat %>% 
      left_join(td_seat, by = c("year", "month", "air_arr")) %>%
      mutate(ArrShare = tcd_seat/td_seat) %>%
      mutate(ArrShare2 = ArrShare^2)
    
    # calculating HHI by airport
    ArrHHI = tcd_seat %>% group_by(year, month, air_arr) %>% 
      dplyr::summarise(ArrHHI = sum(ArrShare2))
    
    # merging all
    tcd_seat = tcd_seat %>% left_join(ArrHHI, by = c("year", "month", "air_arr")) %>%
      select(year, month, air_arr, airline, ArrShare, ArrHHI)
    
    # merging HHI database with BASE1
    BASE1 = BASE1 %>% left_join(tcd_seat, by = c("year", "month", "air_arr", "airline")) 
    
    ## inserting dummies
    
    # editing dummy for tourist airport
    BASE1 = BASE1 %>% mutate(Tourist = case_when(air_arr == "SBAR" ~ TRUE,
                                                air_arr == "SBCB" ~ TRUE,
                                                air_arr == "SBDB" ~ TRUE,
                                                air_arr == "SBFI" ~ TRUE,
                                                air_arr == "SBFN" ~ TRUE,
                                                air_arr == "SBFZ" ~ TRUE,
                                                air_arr == "SBGL" ~ TRUE,
                                                air_arr == "SBGV" ~ TRUE,
                                                air_arr == "SBIL" ~ TRUE,
                                                air_arr == "SBLE" ~ TRUE,
                                                air_arr == "SBPS" ~ TRUE,
                                                air_arr == "SBRF" ~ TRUE,
                                                air_arr == "SBVT" ~ TRUE,
                                                air_arr == "SBFL" ~ TRUE,
                                                TRUE ~ FALSE))
    
    # editing dummy for HUB airport
    BASE1 = BASE1 %>% mutate(ArrHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                                air_arr == "SBGL" ~ TRUE,
                                                air_arr == "SBRJ" ~ TRUE,
                                                air_arr == "SBGR" ~ TRUE,
                                                air_arr == "SBBR" ~ TRUE,
                                                air_arr == "SBFZ" ~ TRUE,
                                                air_arr == "SBRF" ~ TRUE,
                                                air_arr == "SBBH" ~ TRUE,
                                                air_arr == "SBKP" ~ TRUE,
                                                air_arr == "SBEG" ~ TRUE,
                                                TRUE ~ FALSE),
                             DepHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                                air_arr == "SBGL" ~ TRUE,
                                                air_arr == "SBRJ" ~ TRUE,
                                                air_arr == "SBGR" ~ TRUE,
                                                air_arr == "SBBR" ~ TRUE,
                                                air_arr == "SBFZ" ~ TRUE,
                                                air_arr == "SBRF" ~ TRUE,
                                                air_arr == "SBBH" ~ TRUE,
                                                air_arr == "SBKP" ~ TRUE,
                                                air_arr == "SBEG" ~ TRUE,
                                                TRUE ~ FALSE))
    
    # creating hubbling index and aircraft size
    BASE1 = BASE1 %>% mutate(hubling = 1-taxa,
                             aircraft = seat_offer/take_off)
    
    # creating seat and payload capacity index
    BASE1 = BASE1 %>% mutate(tx_seat = nr_rpk/nr_ask,
                             tx_payload = nr_rtk/nr_atk) %>%
      mutate(tx_seat = case_when(tx_seat > 1 ~ 1, 
                                 tx_seat < 0 ~ 0, 
                                 TRUE ~ tx_seat),
             tx_payload = case_when(tx_payload > 1 ~ 1, 
                                    tx_payload < 0 ~ 0, 
                                    TRUE ~ tx_payload))
    
    # importing IPCA database
    IPCA = 
      read_delim(url("https://raw.githubusercontent.com/jrtonin/thesis_data/main/data/parameter/IPCA.csv"), 
                      ";", escape_double = FALSE, 
                      locale = locale(decimal_mark = ",",
                                      grouping_mark = "."), 
                      trim_ws = TRUE) %>% distinct()
    
    # merge IPCA and BASE1 databases
    BASE1 = BASE1 %>% left_join(IPCA, by = c("year", "month")) %>%
      mutate(price = revenue/seat_dem) %>%
      mutate(price = price*Index)
    
    # creating MMC variable
    ## filtering to leader airline
    MMCL = BASE1 %>% 
      filter(N==2) %>%
      arrange(year, month, air_dep, air_arr, airline) %>% 
      group_by(year, month, air_dep, air_arr) %>%
      mutate(id = sequence(n())) %>%
      filter(id == 1) %>%
      select(year, month, air_dep, air_arr, airline) %>%
      mutate(leader = airline) %>% ungroup() %>%
      select(year, month, air_dep, air_arr, leader) 

    ## filtering to followe airline
    MMCS = BASE1 %>% 
      filter(N==2) %>%
      arrange(year, month, air_dep, air_arr, airline) %>% 
      group_by(year, month, air_dep, air_arr) %>%
      mutate(id = sequence(n())) %>%
      filter(id == 2) %>%
      select(year, month, air_dep, air_arr, airline) %>%
      mutate(follower = airline) %>% ungroup() %>%
      select(year, month, air_dep, air_arr, follower)

    ## merging databases
    MMC = MMCL %>% left_join(MMCS, by = c("month", "year", "air_dep", "air_arr"))
    
    ## calculating MMC by companies
    MMS = MMC %>% group_by(year, month, leader, follower) %>% 
      dplyr::summarise(MMC = n()) %>%
      arrange(year, month, desc(MMC))
    
    ## joining final MMC
    MMC = MMC %>% left_join(MMS, by = c("year", "month", "leader", "follower"))
    
    ## merging with BASE1
    BASE1 = BASE1 %>% left_join(MMC %>% select(year, month, air_dep, air_arr, MMC), 
                                by = c("year", "month", "air_dep", "air_arr"))
    
    ## counting airport connection
    NAIRPORT = BASE1 %>% filter(id == 1) %>%
      group_by(year, month, air_dep) %>%
      dplyr::summarise(connection = n())
    
    ## merging with BASE1
    BASE1 = BASE1 %>% left_join(NAIRPORT, by = c("year", "month", "air_dep"))
    
    # setting the directory  
    setwd(dwfinrds) 
    
    ## importing schedule database
    schedule = readRDS("HOUR_Essay_II.rds") %>% distinct() 
    
    ## merging with BASE1
    BASE1 = BASE1 %>% left_join(schedule, by = c("year", "month", "air_dep", 
                                                 "air_arr", "airline")) 
    
    # creating covid dummy
    BASE1 = BASE1 %>%
      mutate(covid = case_when(year == 2020 & month %in% c(3,4,5,6,7,8,9,10,11,12) ~ TRUE,
                               year == 2021 ~ TRUE,
                               TRUE ~ FALSE))
    
    # creating covid wave dummy 
    BASE1 = BASE1 %>%
      mutate(covid_wave = case_when(year == 2020 & month %in% c(3,4,5,6,7,8,9,10,11,12) ~ "first",
                                    year == 2021 & month %in% c(1,2) ~ "first",
                                    year == 2021 & month %in% c(3,4,5,6,7,8,9) ~ "second",
                                    TRUE ~ "normal"))  
    
    # creating quarter dummy
    BASE1 = BASE1 %>% 
      mutate(quarter = case_when(month %in% c(1,2,3) ~ "I",
                                 month %in% c(4,5,6) ~ "II",
                                 month %in% c(7,8,9) ~ "III",
                                 month %in% c(10,11,12) ~ "IV",
                                 TRUE ~ "ERRO"))
    
    # selecting final BASE1 database
    BASE1 = BASE1 %>% ungroup() %>%
      mutate(distance = km_distance/take_off,
             flight_hours = flight_hours/take_off,
             free_luggage = free_luggage/seat_com,
             paid_luggage = paid_luggage/seat_com,
             seat_dir = seat_offer - (seat_bas - seat_com)) %>%
      mutate(distance2 = distance^2,
             tx_dir = seat_dir/seat_offer) %>% 
      mutate(CODE = paste0(air_arr, air_dep))
    
    # inserting arrival airport market structure by airline
    market_arr = BASE1 %>% 
      ungroup() %>%
      group_by(year, month, air_arr, airline) %>%
      dplyr::summarise(revenue = sum(revenue)) %>%
      arrange(year, month, air_arr, desc(revenue)) %>%
      group_by(year, month, air_arr) %>%
      dplyr::mutate(id = sequence(n())) %>%
      dplyr::mutate(market_arr = case_when(id == 1 ~ "lider", TRUE ~ "seguidora")) %>%
      select(-revenue, -id)
    
    # inserting departure airport market structure by airline
    market_dep = BASE1 %>% 
      ungroup() %>%
      group_by(year, month, air_dep, airline) %>%
      dplyr::summarise(revenue = sum(revenue)) %>%
      arrange(year, month, air_dep, desc(revenue)) %>%
      group_by(year, month, air_dep) %>%
      dplyr::mutate(id = sequence(n())) %>%
      dplyr::mutate(market_dep = case_when(id == 1 ~ "lider", TRUE ~ "seguidora")) %>%
      select(-revenue, -id)
  
    # merging database
    BASE1 = BASE1 %>%
      left_join(market_arr, by = c("year", "month", "air_arr", "airline")) %>%
      left_join(market_dep, by = c("year", "month", "air_dep", "airline")) %>%
      arrange(year, month, air_dep, air_arr, airline)
    
    # creating BASE database
    BASE = BASE1
    
    # organizing database
    BASE1 = BASE1 %>% ungroup() %>%
      select(year, month, air_dep, air_arr, CODE, airline, 
             seat_offer, seat_com, seat_bas, seat_dem, seat_free, seat_dir,
             take_off, aircraft, flight_hours, distance, distance2, weight, lt_fuel,
             revenue, price, hubling, mail, free_luggage, paid_luggage, 
             tx_seat, tx_payload, seat_fuel, payload_fuel, N, tx_dir,
             RouteShare, DepShare, ArrShare, FreqShare, 
             RouteHHI, DepHHI, ArrHHI, FreqHHI,
             Tourist, ArrHUB, DepHUB, market, MMC, connection,
             `0-5`, `6-11`, `12-17`, `18-23`, covid, quarter,
             market_arr, market_dep, covid_wave) %>%
      ungroup() %>%
      arrange(year, month, air_dep, air_arr, airline) %>%
      mutate(id = sequence(n()))
    
    # applying log
    LBASE1 = BASE1 %>% mutate(seat_offer = log(seat_offer), 
                              seat_com = log(seat_com), 
                              seat_bas = log(seat_bas), 
                              seat_dem = log(seat_dem), 
                              seat_free = log(seat_free),
                              seat_dir = log(seat_dir),
                              revenue = log(revenue), 
                              price = log(price),
                              take_off = log(take_off), 
                              hubling = log(hubling), 
                              lt_fuel = log(lt_fuel),
                              mail = log(mail), 
                              weight = log(weight), 
                              tx_seat = log(1+tx_seat), 
                              tx_payload = log(1+tx_payload),
                              tx_dir = log(tx_dir),
                              aircraft = log(aircraft),
                              flight_hours = log(1+flight_hours),
                              RouteShare = log(RouteShare), 
                              FreqHHI = log(FreqHHI), 
                              RouteHHI = log(RouteHHI), 
                              DepHHI = log(DepHHI), 
                              ArrHHI = log(ArrHHI),
                              DepShare = log(DepShare),
                              ArrShare = log(ArrShare),
                              FreqShare = log(FreqShare),
                              seat_fuel = log(seat_fuel),
                              payload_fuel = log(payload_fuel),
                              MMC = log(MMC),
                              connection = log(connection),
                              distance = log(distance), 
                              distance2 = log(distance2), 
                              flight_hours = log(flight_hours),
                              free_luggage = log(1 + free_luggage),
                              paid_luggage = log(1 + paid_luggage))
    
    # transforming inf to 0
    is.na(LBASE1) = sapply(LBASE1, is.infinite)
    LBASE1[is.na(LBASE1)] = 0
    
    } # organizing BASE1 and LBASE1 databases
  
  {
    # pre-organizing BASE2 database
    BASE2 = BASE %>% filter(N == 2)
    
    # filtering leader and follower companies
    lider = BASE2 %>% filter(market == "lider")
    seguidora = BASE2 %>% filter(market == "seguidora")
    
    # joining leader and follower companies with BASE2 database
    BASE2 = left_join(lider, seguidora, by = c("year", "month", "air_arr", "air_dep")) %>%
      mutate(CODE = paste0(air_arr, air_dep))
    
    # calculating the difference of leader and follower companies data
    BASE2 = BASE2 %>% mutate(seat_offer = seat_offer.x - seat_offer.y,
                             seat_com = seat_com.x - seat_com.y,
                             seat_bas = seat_bas.x - seat_bas.y,
                             seat_dem = seat_dem.x - seat_dem.y,
                             seat_free = seat_free.x - seat_free.y,
                             seat_dir = seat_dir.x - seat_dir.y,
                             take_off = take_off.x - take_off.y,
                             aircraft = aircraft.x - aircraft.y,
                             flight_hours = flight_hours.x - flight_hours.y,
                             weight = weight.x - weight.y,
                             lt_fuel = lt_fuel.x - lt_fuel.y,
                             revenue = revenue.x - revenue.y,
                             price = price.x - price.y,
                             hubling = hubling.x - hubling.y, 
                             mail = mail.x - mail.y,
                             free_luggage = free_luggage.x - free_luggage.y,
                             paid_luggage = paid_luggage.x - paid_luggage.y,
                             tx_seat = tx_seat.x - tx_seat.y,
                             tx_payload = tx_payload.x - tx_payload.y,
                             tx_dir = tx_dir.x - tx_dir.y,
                             seat_fuel = seat_fuel.x - seat_fuel.x,
                             payload_fuel = payload_fuel.x - payload_fuel.y,
                             `0-5` = `0-5.x` - `0-5.y`,
                             `6-11` = `6-11.x` - `6-11.y`,
                             `12-17` = `12-17.x` - `12-17.y`,
                             `18-23` = `18-23.x` - `18-23.y`) %>%
      group_by(year, month, air_arr, air_dep) %>%
      select(year, month, air_arr, air_dep,
             seat_offer, seat_com, seat_bas, seat_dem, seat_free, seat_dir,
             take_off, aircraft, flight_hours, weight, lt_fuel,
             revenue, price, hubling, mail, free_luggage, paid_luggage,
             tx_seat, tx_payload, seat_fuel, payload_fuel, 
             `0-5`, `6-11`, `12-17`, `18-23`)
    
    # editing the CONTROL database (basic information of routes)
    CONTROL = BASE %>% group_by(year, month, air_arr, air_dep) %>% 
      dplyr::summarise(FreqHHI = mean(FreqHHI),
                       RouteHHI = mean(RouteHHI),
                       ArrHHI = mean(ArrHHI),
                       DepHHI = mean(DepHHI),
                       distance = mean(distance),
                       distance2 = mean(distance2),
                       MMC = mean(MMC),
                       connection = mean(connection))
    
    # merging CONTROL and BASE2 databases
    BASE2 = BASE2 %>% left_join(CONTROL, by = c("year", "month", "air_dep", "air_arr"))
    
    # editing dummy of tourist airports 
    BASE2 = BASE2 %>% mutate(Tourist = case_when(air_dep == "SBAR" ~ TRUE,
                                                air_dep == "SBCB" ~ TRUE,
                                                air_dep == "SBDB" ~ TRUE,
                                                air_dep == "SBFI" ~ TRUE,
                                                air_dep == "SBFN" ~ TRUE,
                                                air_dep == "SBFZ" ~ TRUE,
                                                air_dep == "SBGL" ~ TRUE,
                                                air_dep == "SBGV" ~ TRUE,
                                                air_dep == "SBIL" ~ TRUE,
                                                air_dep == "SBLE" ~ TRUE,
                                                air_dep == "SBPS" ~ TRUE,
                                                air_dep == "SBRF" ~ TRUE,
                                                air_dep == "SBVT" ~ TRUE,
                                                air_dep == "SBFL" ~ TRUE,
                                                TRUE ~ FALSE))
    # editing dummy of HUB airports 
    BASE2 = BASE2 %>% mutate(ArrHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                                air_arr == "SBGL" ~ TRUE,
                                                air_arr == "SBRJ" ~ TRUE,
                                                air_arr == "SBGR" ~ TRUE,
                                                air_arr == "SBBR" ~ TRUE,
                                                air_arr == "SBFZ" ~ TRUE,
                                                air_arr == "SBRF" ~ TRUE,
                                                air_arr == "SBBH" ~ TRUE,
                                                air_arr == "SBKP" ~ TRUE,
                                                air_arr == "SBEG" ~ TRUE,
                                                TRUE ~ FALSE),
                             DepHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                                air_arr == "SBGL" ~ TRUE,
                                                air_arr == "SBRJ" ~ TRUE,
                                                air_arr == "SBGR" ~ TRUE,
                                                air_arr == "SBBR" ~ TRUE,
                                                air_arr == "SBFZ" ~ TRUE,
                                                air_arr == "SBRF" ~ TRUE,
                                                air_arr == "SBBH" ~ TRUE,
                                                air_arr == "SBKP" ~ TRUE,
                                                air_arr == "SBEG" ~ TRUE,
                                                TRUE ~ FALSE))
    
    # creating covid dummy
    BASE2 = BASE2 %>%
      mutate(covid = case_when(year == 2020 & month %in% c(3,4,5,6,7,8,9,10,11,12) ~ TRUE,
                               year == 2021 ~ TRUE,
                               TRUE ~ FALSE))
    # creating covid wave dummy 
    BASE2 = BASE2 %>%
      mutate(covid_wave = case_when(year == 2020 & month %in% c(3,4,5,6,7,8,9,10,11,12) ~ "first",
                                    year == 2021 & month %in% c(1,2) ~ "first",
                                    year == 2021 & month %in% c(3,4,5,6,7,8,9) ~ "second",
                                    TRUE ~ "normal")) 
    # creating quarter dummy
    BASE2 = BASE2 %>% 
      mutate(quarter = case_when(month %in% c(1,2,3) ~ "I",
                                 month %in% c(4,5,6) ~ "II",
                                 month %in% c(7,8,9) ~ "III",
                                 month %in% c(10,11,12) ~ "IV",
                                 TRUE ~ "ERRO")) %>% 
      mutate(CODE = paste0(air_arr, air_dep))
    
    ## summarizing BASE2 and applying log 
    LBASE2 = LBASE1 %>% filter(N == 2)
    
    # transforming inf data in 0
    is.na(LBASE2) = sapply(LBASE2, is.infinite)
    LBASE2[is.na(LBASE2)] = 0
    
    # filtering leader and follower companies
    lider = LBASE2 %>% filter(market == "lider")
    seguidora = LBASE2 %>% filter(market == "seguidora")
    
    # merging leader and follower database with LBASE2
    LBASE2 = left_join(lider, seguidora, by = c("year", "month", "air_arr", "air_dep")) 
    
    # calculating the difference of leader and follower companies data
    LBASE2 = LBASE2 %>% mutate(seat_offer = seat_offer.x - seat_offer.y,
                             seat_com = seat_com.x - seat_com.y,
                             seat_bas = seat_bas.x - seat_bas.y,
                             seat_dem = seat_dem.x - seat_dem.y,
                             seat_free = seat_free.x - seat_free.y,
                             seat_dir = seat_dir.x - seat_dir.y,
                             take_off = take_off.x - take_off.y,
                             aircraft = aircraft.x - aircraft.y,
                             flight_hours = flight_hours.x - flight_hours.y,
                             weight = weight.x - weight.y,
                             lt_fuel = lt_fuel.x - lt_fuel.y,
                             revenue = revenue.x - revenue.y,
                             price = price.x - price.y,
                             hubling = hubling.x - hubling.y, 
                             mail = mail.x - mail.y,
                             free_luggage = free_luggage.x - free_luggage.y,
                             paid_luggage = paid_luggage.x - paid_luggage.y,
                             tx_seat = tx_seat.x - tx_seat.y,
                             tx_payload = tx_payload.x - tx_payload.y,
                             tx_dir = tx_dir.x - tx_dir.y,
                             RouteShare = RouteShare.x - RouteShare.y,
                             seat_fuel = seat_fuel.x - seat_fuel.x,
                             payload_fuel = payload_fuel.x - payload_fuel.y,
                             `0-5` = `0-5.x` - `0-5.y`,
                             `6-11` = `6-11.x` - `6-11.y`,
                             `12-17` = `12-17.x` - `12-17.y`,
                             `18-23` = `18-23.x` - `18-23.y`) %>%
      group_by(year, month, air_arr, air_dep) %>%
      select(year, month, air_arr, air_dep,
             seat_offer, seat_com, seat_bas, seat_dem, seat_free, seat_dir,
             take_off, aircraft, flight_hours, weight, lt_fuel,
             revenue, price, hubling, mail, free_luggage, paid_luggage,
             tx_seat, tx_payload, seat_fuel, payload_fuel, RouteShare,
             `0-5`, `6-11`, `12-17`, `18-23`)
    
    # editing the CONTROL database (basic information of routes)
    CONTROL = BASE %>% group_by(year, month, air_arr, air_dep) %>% 
      dplyr::summarise(FreqHHI = log(mean(FreqHHI)),
                       RouteHHI = log(mean(RouteHHI)),
                       ArrHHI = log(mean(ArrHHI)),
                       DepHHI = log(mean(DepHHI)),
                       MMC = log(mean(MMC)),
                       connection = log(mean(connection)))
    
    # merging CONTROL and LBASE2 databases
    LBASE2 = LBASE2 %>% left_join(CONTROL, by = c("year", "month", "air_dep", "air_arr"))
    
    # editing dummy of tourist airports 
    LBASE2 = LBASE2 %>% mutate(Tourist = case_when(air_dep == "SBAR" ~ TRUE,
                                                  air_dep == "SBCB" ~ TRUE,
                                                  air_dep == "SBDB" ~ TRUE,
                                                  air_dep == "SBFI" ~ TRUE,
                                                  air_dep == "SBFN" ~ TRUE,
                                                  air_dep == "SBFZ" ~ TRUE,
                                                  air_dep == "SBGL" ~ TRUE,
                                                  air_dep == "SBGV" ~ TRUE,
                                                  air_dep == "SBIL" ~ TRUE,
                                                  air_dep == "SBLE" ~ TRUE,
                                                  air_dep == "SBPS" ~ TRUE,
                                                  air_dep == "SBRF" ~ TRUE,
                                                  air_dep == "SBVT" ~ TRUE,
                                                  air_dep == "SBFL" ~ TRUE,
                                                  TRUE ~ FALSE))
    # editing dummy of HUB airports 
    LBASE2 = LBASE2 %>% mutate(ArrHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                                  air_arr == "SBGL" ~ TRUE,
                                                  air_arr == "SBRJ" ~ TRUE,
                                                  air_arr == "SBGR" ~ TRUE,
                                                  air_arr == "SBBR" ~ TRUE,
                                                  air_arr == "SBFZ" ~ TRUE,
                                                  air_arr == "SBRF" ~ TRUE,
                                                  air_arr == "SBBH" ~ TRUE,
                                                  air_arr == "SBKP" ~ TRUE,
                                                  air_arr == "SBEG" ~ TRUE,
                                                  TRUE ~ FALSE),
                               DepHUB = case_when(air_arr == "SBSP" ~ TRUE,
                                                  air_arr == "SBGL" ~ TRUE,
                                                  air_arr == "SBRJ" ~ TRUE,
                                                  air_arr == "SBGR" ~ TRUE,
                                                  air_arr == "SBBR" ~ TRUE,
                                                  air_arr == "SBFZ" ~ TRUE,
                                                  air_arr == "SBRF" ~ TRUE,
                                                  air_arr == "SBBH" ~ TRUE,
                                                  air_arr == "SBKP" ~ TRUE,
                                                  air_arr == "SBEG" ~ TRUE,
                                                  TRUE ~ FALSE)) %>%
      mutate(CODE = paste0(air_arr,air_dep))
    
    # creating covid dummy
    LBASE2 = LBASE2 %>%
      mutate(covid = case_when(year == 2020 & month %in% c(3,4,5,6,7,8,9,10,11,12) ~ TRUE,
                               year == 2021 ~ TRUE,
                               TRUE ~ FALSE))
    
    # creating covid wave dummy 
    LBASE2 = LBASE2 %>%
      mutate(covid_wave = case_when(year == 2020 & month %in% c(3,4,5,6,7,8,9,10,11,12) ~ "first",
                                    year == 2021 & month %in% c(1,2) ~ "first",
                                    year == 2021 & month %in% c(3,4,5,6,7,8,9) ~ "second",
                                    TRUE ~ "normal")) 
    # creating quarter dummy
    LBASE2 = LBASE2 %>% 
      mutate(quarter = case_when(month %in% c(1,2,3) ~ "I",
                                 month %in% c(4,5,6) ~ "II",
                                 month %in% c(7,8,9) ~ "III",
                                 month %in% c(10,11,12) ~ "IV",
                                 TRUE ~ "ERRO")) %>%
      mutate(CODE = paste0(air_arr, air_dep))
    
    } # organizing BASE2 and LBASE2 databases
  
} # Transforming final databases - quick cleaning

{
  # setting the directory  
  setwd(dwfinrds) 
  
  saveRDS(BASE1, "BASE1_Essay_II.rds")
  saveRDS(BASE2, "BASE2_Essay_II.rds")
  saveRDS(LBASE1, "LBASE1_Essay_II.rds")
  saveRDS(LBASE2, "LBASE2_Essay_II.rds")
  saveRDS(BASE, "BASE_Essay_II.rds")
} # saving databases

```

```{r reading_databases, include=FALSE, echo=TRUE}

# setting directories
setwd(dwfinrds)

# reading databases
BASE1 = readRDS("BASE1_Essay_II.rds")
BASE2 = readRDS("BASE2_Essay_II.rds")
LBASE1 = readRDS("LBASE1_Essay_II.rds")
LBASE2 = readRDS("LBASE2_Essay_II.rds")
BASE = readRDS("BASE_Essay_II.rds")
FINAL = readRDS("FINAL_Essay_II.rds")

```

```{r HAUSMAN_instruments, include=FALSE}

# organizing database
ROUTES = BASE1 %>%
  group_by(air_arr, air_dep) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::select(-n)

# importing aerodromo database
aerodromos = 
  read_delim(url("https://raw.githubusercontent.com/jrtonin/thesis_data/main/data/parameter/AERODROMOS.csv"), 
                        delim = ";", escape_double = FALSE, 
                        locale = locale(encoding = "ISO-8859-1"), 
                        trim_ws = TRUE)

# importing lat and lon by city
urlfile = "https://raw.githubusercontent.com/kelvins/Municipios-Brasileiros/main/csv/municipios.csv"
latlon = read_csv(url(urlfile)) %>%
  mutate(code_city = codigo_ibge,
         lat = latitude,
         lon = longitude,
         city = nome,
         uf_code = codigo_uf) %>% 
  dplyr::select(code_city, city, uf_code, lat, lon)

# including IBGE code and lat and lon
aerodromos = aerodromos %>%
  left_join(latlon, by = c("city", "uf_code")) 


# summarizing end points
endpointa = ROUTES %>% 
  group_by(air_dep) %>% 
  dplyr::summarise(n = n()) %>% 
  dplyr::select(-n) %>%
  left_join(aerodromos %>% dplyr::select(code, code_city), 
            by = c("air_dep" = "code")) %>%
  group_by(code_city) %>%
  dplyr::summarise(n = n()) %>% 
  ungroup() %>%
  dplyr::select(-n)

# summarizing pre points
endpointb = ROUTES %>% 
  group_by(air_arr) %>% 
  dplyr::summarise(n = n()) %>% 
  dplyr::select(-n) %>%
  left_join(aerodromos %>% dplyr::select(code, code_city), by = c("air_arr" = "code")) %>%
  group_by(code_city) %>%
  dplyr::summarise(n = n()) %>% 
  ungroup() %>%
  dplyr::select(-n)

# edditing final endpoint database
endpoint = endpointa %>% bind_rows(endpointb) %>%
  group_by(code_city) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::select(-n)

# transforming endpoint to vector
vendpoint = as.vector(endpoint$code_city)

# combining endpoints
DISTANCES = as.data.frame(t(as.matrix(combn(vendpoint, 2)))) %>%
  filter(!is.na(V1) | !is.na(V2)) %>%
  mutate(filter = case_when(V1 == V2 ~ TRUE, TRUE ~ FALSE)) %>%
  filter(filter == FALSE) %>%
  left_join(aerodromos %>% select(code_city, lat, lon), by = c("V1" = "code_city")) %>%
  mutate(lat_arr = lat, lon_arr = lon, arr = V1, dep = V2) %>%
  select(arr, dep, lat_arr, lon_arr) %>%
  left_join(aerodromos %>% select(code_city, lat, lon), by = c("dep" = "code_city")) %>%
  mutate(lat_dep = lat, lon_dep = lon) %>%
  select(arr, lat_arr, lon_arr, dep, lat_dep, lon_dep) %>%
  rowwise() %>%
  dplyr::mutate(distance = distm(x = c(lon_arr, lat_arr), 
                                 y = c(lon_dep, lat_dep), 
                                 fun = distHaversine)/1000) %>%
  distinct() %>%
  mutate(distance = round(distance, 0)) 

# generating final DISTANCES database
DISTANCES = DISTANCES %>% 
  mutate(air_dep = dep, air_arr = arr) %>% 
  select(air_arr, air_dep, distance) %>%
  bind_rows(DISTANCES %>% 
              mutate(air_dep = arr, air_arr = dep) %>% 
              select(air_arr, air_dep, distance))

# generating pre database
BASEF = BASE1 %>% 
  mutate(yearmonth = paste0(year, month)) %>%
  select(air_dep, air_arr, airline, DepHHI, RouteHHI, seat_dem, price, 
         RouteShare,  id, yearmonth) %>%
  ungroup() %>%
  left_join(aerodromos %>% select(code, code_city), by = c("air_dep" = "code")) %>%
  mutate(dep_code_city = code_city) %>% select(-code_city) %>%
  left_join(aerodromos %>% select(code, code_city), by = c("air_arr" = "code")) %>%
  mutate(arr_code_city = code_city) %>% select(-code_city)  

# creating id vector
id = as.vector(BASEF$id)

# editing looping 
for (file in 1:31203){ 

  # filtering airline variable
  cia = BASEF %>% filter(id == id[file])
  cia = as.vector(cia$airline)
  
  # filtering time variable
  ym = BASEF %>% filter(id == id[file])
  ym = as.vector(ym$yearmonth) 
  
  # filtering airport variable
  airport = BASEF %>% filter(id == id[file])
  airport = as.vector(airport$arr_code_city)
  
  # filtering airline and time in BASEF database
  BASE = BASEF %>% filter(airline %in% cia & yearmonth %in% ym)
  
  # filtering airports with distances greater than 150 km to arrival airport
  distance150 = DISTANCES %>% filter(air_arr %in% airport & distance > 150)
  airportarr = as.vector(distance150$air_dep) 
  
  # summarizing DepHHI mean of routes
  distance150 = BASE %>% filter(arr_code_city %in% airportarr) %>%
    dplyr::summarise(m150DepHHI = mean(DepHHI),
                     m150RouteHHI = mean(RouteHHI),
                     m150seat_dem = mean(seat_dem),
                     m150price = mean(price),
                     m150RouteShare = mean(RouteShare)) %>%
    mutate(id = id[file])
  
  # filtering airports with distances greater than 300 km to arrival airport
  distance300 = DISTANCES %>% filter(air_arr %in% airport & distance > 300)
  airportarr = as.vector(distance300$air_dep) 
  
  # summarizing DepHHI mean of routes
  distance300 = BASE %>% filter(arr_code_city %in% airportarr) %>%
    dplyr::summarise(m300DepHHI = mean(DepHHI),
                     m300RouteHHI = mean(RouteHHI),
                     m300seat_dem = mean(seat_dem),
                     m300price = mean(price),
                     m300RouteShare = mean(RouteShare)) %>%
    mutate(id = id[file])
  
  # filtering airports with distances greater than 500 km to arrival airport
  distance500 = DISTANCES %>% filter(air_arr %in% airport & distance > 500)
  airportarr = as.vector(distance500$air_dep) 
  
  # summarizing DepHHI mean of routes
  distance500 = BASE %>% filter(arr_code_city %in% airportarr) %>%
    dplyr::summarise(m500DepHHI = mean(DepHHI),
                     m500RouteHHI = mean(RouteHHI),
                     m500seat_dem = mean(seat_dem),
                     m500price = mean(price),
                     m500RouteShare = mean(RouteShare)) %>%
    mutate(id = id[file])
  
  # merging final database
  final = distance150 %>%
    left_join(distance300, by = ("id")) %>%
    left_join(distance500, by = ("id"))
  
  # setting the directory      
  setwd(dwhaurds) 
    
  # Saving a single object to a file
  saveRDS(final, paste(file, ".rds"))
  
  } # Creating looping

 {
    # Step 1: set the working directory (where files are saved)
    setwd(dwhaurds) 
    
    # Step 2: get all the right file names
    file_names = list.files(getwd())
    file_names = file_names[grepl(".rds",file_names)]
    
    # Step 3: get the read.csv function working
    files = readRDS("1 .rds")
    
    # Step 4: use lapply to apply the read.csv function to all values of file_names
    files = lapply(file_names, readRDS)
    list = files
    files = rbindlist(files, fill = TRUE)
    
    # check structure of new data set
    str(files)
    
    # rename
    INSTRUMENT = files
    
  } # Join databases

  # setting the directory      
  setwd(dwfinrds) 
  
  # Saving a single object to a file
  saveRDS(INSTRUMENT, "HAUSMAN_instrument.rds")

```

```{r ESTBAN_instruments, include = FALSE}

  # setting the directory  
  setwd(dwestraw) 
  
  # creating a list of .CSV databases
  temp = list.files(pattern = "*.CSV") 
  
  for (file in 1:35){ 

    # setting the directory    
    setwd(dwestraw) 
    
    # get the read_delim function working
    vfiles = read_delim(temp[file], delim = ";", escape_double = FALSE, 
                    locale = locale(decimal_mark = ",",
                                    grouping_mark = ".", 
                                    encoding = "ISO-8859-1"), 
                    trim_ws = TRUE, skip = 2)
    
    # organizing database
    ESTBAN = vfiles %>%
      select(CODMUN_IBGE, AGEN_ESPERADAS, VERBETE_112_DEPOSITOS_BANCARIOS,
             VERBETE_160_OPERACOES_DE_CREDITO, VERBETE_162_FINANCIAMENTOS, `#DATA_BASE`) %>%
        mutate(code_city = CODMUN_IBGE,
               nbank = AGEN_ESPERADAS,
               deposits = VERBETE_112_DEPOSITOS_BANCARIOS,
               credit = VERBETE_160_OPERACOES_DE_CREDITO,
               loan = VERBETE_162_FINANCIAMENTOS,
               time = `#DATA_BASE`) %>%
      group_by(code_city, time) %>%
      dplyr::summarise(nbank = sum(nbank),
                       deposits = sum(deposits),
                       credit = sum(credit),
                       loan = sum(loan))
      
    # setting the directory      
    setwd(dwestrds) 
    
    # Saving a single object to a file
    saveRDS(ESTBAN, paste(file, ".rds"))
 
  } # Creating looping for .txt files
  
  {
    # Step 1: set the working directory (where files are saved)
    setwd(dwestrds) 
    
    # Step 2: get all the right file names
    file_names = list.files(getwd())
    file_names = file_names[grepl(".rds",file_names)]
    
    # Step 3: get the read.csv function working
    files = readRDS("1 .rds")
    
    # Step 4: use lapply to apply the read.csv function to all values of file_names
    files = lapply(file_names, readRDS)
    list = files
    files = rbindlist(files, fill = TRUE)
    
    # check structure of new data set
    str(files)
    
    # rename
    ESTBAN = files
    
    
  } # Join databases
  
  # Dropping unnecessary databases
  remove(list = c("files", "file_names"))
  
  # including credit_loan variable
  ESTBAN = ESTBAN %>% mutate(credit_loan = credit + loan)
  
  # setting the directory      
  setwd(dwfinrds) 
  
  # Saving a single object to a file
  saveRDS(ESTBAN, "ESTBAN_instrument.rds")
  
```

```{r merge_instruments, include=FALSE}

# importing aerodromo database
aerodromos = read_delim(url("https://raw.githubusercontent.com/jrtonin/thesis_essay_ii/main/data/aerodromos.csv"), 
                        delim = ";", escape_double = FALSE, 
                        locale = locale(encoding = "ISO-8859-1"), 
                        trim_ws = TRUE)

# importing lat and lon by city
urlfile = "https://raw.githubusercontent.com/kelvins/Municipios-Brasileiros/main/csv/municipios.csv"
latlon = read_csv(url(urlfile)) %>%
  mutate(code_city = codigo_ibge,
         lat = latitude,
         lon = longitude,
         city = nome,
         uf_code = codigo_uf) %>% 
  dplyr::select(code_city, city, uf_code, lat, lon)

# including IBGE code and lat and lon
aerodromos = aerodromos %>%
  left_join(latlon, by = c("city", "uf_code"))

# changing NA's
HAUSMAN[is.na(HAUSMAN)] = 0

# merging ESTBAN and HAUSMAN data
LBASE1a = LBASE1 %>%
  left_join(aerodromos %>% dplyr::select(code, code_city), by = c("air_dep" = "code")) %>%
  mutate(code_city_dep = code_city) %>% dplyr::select(-code_city) %>%
  left_join(aerodromos %>% dplyr::select(code, code_city), by = c("air_arr" = "code")) %>%
  mutate(code_city_arr = code_city) %>% dplyr::select(-code_city) %>% 
  left_join(ESTBAN %>% 
            mutate(year = as.double(str_sub(time, 1,4)),
                   month = as.double(str_sub(time, 5, 6))) %>%
              dplyr::select(year, month, code_city, nbank, deposits, credit_loan), 
            by = c("code_city_dep" = "code_city", "year" = "year", "month" = "month")) %>%
  mutate(ldep_nbank = log(nbank),
         ldep_deposits = log(deposits+1),
         ldep_credit_loan = log(credit_loan)) %>% 
  dplyr::select(-nbank, -deposits, -credit_loan) %>%
  left_join(ESTBAN %>% 
            mutate(year = as.double(str_sub(time, 1,4)),
                   month = as.double(str_sub(time, 5, 6))) %>%
              dplyr::select(year, month, code_city, nbank, deposits, credit_loan), 
            by = c("code_city_arr" = "code_city", "year" = "year", "month" = "month")) %>%
  mutate(larr_nbank = log(nbank),
         larr_deposits = log(deposits+1),
         larr_credit_loan = log(credit_loan)) %>% 
  dplyr::select(-nbank, -deposits, -credit_loan) %>%
  mutate(nbank = (larr_nbank*ldep_nbank)^1/2,
         deposits = (ldep_deposits*larr_deposits)^1/2,
         credit_loan = (ldep_credit_loan*larr_credit_loan)^1/2) %>%
  dplyr::select(-larr_nbank, -larr_deposits, -larr_credit_loan, 
                -ldep_nbank, -ldep_deposits, -ldep_credit_loan) %>%
  mutate(id = sequence(n())) %>% 
  left_join(HAUSMAN, by = c("id")) %>%
  mutate(m150RouteHHI = log(m150RouteHHI+1), 
         m300RouteHHI = log(m300RouteHHI+1),
         m500RouteHHI = log(m500RouteHHI+1),
         m150DepHHI = log(m150DepHHI+1),
         m300DepHHI = log(m300DepHHI+1),
         m500DepHHI = log(m500DepHHI+1),
         m150seat_dem = log(m150seat_dem+1),
         m300seat_dem = log(m300seat_dem+1),
         m500seat_dem = log(m500seat_dem+1),
         m150price = log(m150price+1),
         m300price = log(m300price+1),
         m500price = log(m500price+1),
         m150RouteShare = log(m150RouteShare+1), 
         m300RouteShare = log(m300RouteShare+1),
         m500RouteShare = log(m500RouteShare+1))

# changing NA's
 LBASE1a[is.na(LBASE1a)] = 0

```


